//! `m2_stcortex_consumer` — workflow-trace's narrowed-scope consumer for
//! stcortex (SpacetimeDB at `ws://127.0.0.1:3000`).
//!
//! See [m2 spec](../../../ai_specs/modules/cluster-D/m2_stcortex_consumer.md).
//!
//! # Day-1 surface
//!
//! - [`ConsumerName`] / [`Namespace`] / [`Transport`] / [`ConsumerIdentity`]
//!   newtypes — AP30 enforcement lives in the type system.
//! - [`tool_call_query`] / [`consumption_event_query`] — the **only two**
//!   narrowed subscription queries. W1 invariant: subscription strings
//!   are hardcoded; widening to `pathway` / `memory` requires a v1.4
//!   spec amendment (and re-evaluation of F8 Watcher feedback-loop
//!   poisoning).
//! - [`register_narrowed_consumer`] — synchronous entry point. Builds a
//!   `DbConnection`, invokes `register_consumer`, subscribes, waits for
//!   `on_applied`.
//! - [`RegistrationHandle::is_fresh`] — the CC-2 trust-signal gate that
//!   m13 reads before every write attempt.
//! - [`StcortexRow`] / [`ToolCallRow`] / [`ConsumptionEventRow`] — typed
//!   delta row mirrors (callback payloads).
//!
//! # Vendored module_bindings
//!
//! `module_bindings/` is a verbatim copy of
//! `stcortex/clients/rust-subscriber/src/module_bindings/` (generated by
//! the SpacetimeDB CLI). It mirrors the live stcortex schema as of the
//! copy date. Regenerate on schema change. The submodule is private to
//! this crate.

// Module-level allow flags for the vendored generated bindings — they
// trip a number of clippy pedantic lints (acronyms in prose, unused
// items, etc.). Generated code is OUT OF SCOPE for god-tier gating.
#[allow(
    unused,
    dead_code,
    clippy::all,
    clippy::pedantic,
    clippy::doc_markdown,
    clippy::missing_safety_doc,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::module_name_repetitions,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::type_complexity,
    clippy::wildcard_imports,
    clippy::redundant_closure_for_method_calls,
    clippy::needless_pass_by_value,
    clippy::must_use_candidate,
    clippy::semicolon_if_nothing_returned,
    clippy::trivially_copy_pass_by_ref,
    clippy::derive_partial_eq_without_eq,
    missing_docs,
    unexpected_cfgs
)]
mod module_bindings;

pub mod error;
pub mod identity;
pub mod row;
pub mod subscription;

pub use error::StcortexConsumerError;
pub use identity::{
    ConsumerIdentity, ConsumerName, Namespace, Transport, CONSUMER_NAME_MAX_LEN,
    WORKFLOW_TRACE_PREFIX,
};
pub use row::{ConsumptionEventRow, StcortexRow, ToolCallRow};
pub use subscription::{
    consumption_event_query, register_narrowed_consumer, tool_call_query, RegistrationHandle,
    DEFAULT_SUBSCRIPTION_TIMEOUT_MS, STCORTEX_DB, STCORTEX_URI,
};

#[cfg(test)]
mod tests {
    use super::{
        consumption_event_query, tool_call_query, ConsumerIdentity, ConsumerName, Namespace,
        StcortexConsumerError, Transport, WORKFLOW_TRACE_PREFIX,
    };

    #[test]
    fn reexports_prefix_constant() {
        // Re-exported from m9's single source of truth.
        assert_eq!(
            WORKFLOW_TRACE_PREFIX,
            crate::m9_watcher_namespace_guard::WORKFLOW_TRACE_NS_PREFIX
        );
    }

    #[test]
    fn reexports_consumer_name_validator() {
        assert!(ConsumerName::new("workflow-trace-abc").is_ok());
        assert!(matches!(
            ConsumerName::new(""),
            Err(StcortexConsumerError::InvalidConsumerName(_))
        ));
    }

    #[test]
    fn reexports_namespace_validator() {
        assert!(Namespace::new("workflow_trace_x").is_ok());
        assert!(matches!(
            Namespace::new("orac_foo"),
            Err(StcortexConsumerError::InvalidNamespace(_))
        ));
    }

    #[test]
    fn reexports_transport_subscription_only() {
        assert_eq!(Transport::Subscription.as_str(), "subscription");
    }

    #[test]
    fn reexports_query_builders() {
        let q = tool_call_query(WORKFLOW_TRACE_PREFIX);
        assert!(q.contains("LIKE"));
        assert!(q.contains(WORKFLOW_TRACE_PREFIX));
        assert_eq!(consumption_event_query(), "SELECT * FROM consumption_event");
    }

    #[test]
    fn from_git_sha_uses_workflow_trace_prefix() {
        let ns = Namespace::new("workflow_trace_test").unwrap();
        let id = ConsumerIdentity::from_git_sha(ns);
        assert!(id.name.as_str().starts_with("workflow-trace-"));
    }
}
