// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AccessMemoryArgs {
    pub memory_id: u64,
    pub consumer_name: String,
}

impl From<AccessMemoryArgs> for super::Reducer {
    fn from(args: AccessMemoryArgs) -> Self {
        Self::AccessMemory {
            memory_id: args.memory_id,
            consumer_name: args.consumer_name,
        }
    }
}

impl __sdk::InModule for AccessMemoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `access_memory`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait access_memory {
    /// Request that the remote module invoke the reducer `access_memory` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`access_memory:access_memory_then`] to run a callback after the reducer completes.
    fn access_memory(&self, memory_id: u64, consumer_name: String) -> __sdk::Result<()> {
        self.access_memory_then(memory_id, consumer_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `access_memory` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn access_memory_then(
        &self,
        memory_id: u64,
        consumer_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl access_memory for super::RemoteReducers {
    fn access_memory_then(
        &self,
        memory_id: u64,
        consumer_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AccessMemoryArgs {
                memory_id,
                consumer_name,
            },
            callback,
        )
    }
}
