// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddCrossSubstrateRefArgs {
    pub memory_id: u64,
    pub substrate: String,
    pub uri: String,
    pub anchor: Option<String>,
}

impl From<AddCrossSubstrateRefArgs> for super::Reducer {
    fn from(args: AddCrossSubstrateRefArgs) -> Self {
        Self::AddCrossSubstrateRef {
            memory_id: args.memory_id,
            substrate: args.substrate,
            uri: args.uri,
            anchor: args.anchor,
        }
    }
}

impl __sdk::InModule for AddCrossSubstrateRefArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_cross_substrate_ref`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_cross_substrate_ref {
    /// Request that the remote module invoke the reducer `add_cross_substrate_ref` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_cross_substrate_ref:add_cross_substrate_ref_then`] to run a callback after the reducer completes.
    fn add_cross_substrate_ref(
        &self,
        memory_id: u64,
        substrate: String,
        uri: String,
        anchor: Option<String>,
    ) -> __sdk::Result<()> {
        self.add_cross_substrate_ref_then(memory_id, substrate, uri, anchor, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_cross_substrate_ref` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_cross_substrate_ref_then(
        &self,
        memory_id: u64,
        substrate: String,
        uri: String,
        anchor: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl add_cross_substrate_ref for super::RemoteReducers {
    fn add_cross_substrate_ref_then(
        &self,
        memory_id: u64,
        substrate: String,
        uri: String,
        anchor: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddCrossSubstrateRefArgs {
                memory_id,
                substrate,
                uri,
                anchor,
            },
            callback,
        )
    }
}
