// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentRegistry {
    pub agent_id: String,
    pub namespace: String,
    pub display_name: String,
    pub actor_kind: String,
    pub role_class: String,
    pub status: String,
    pub capabilities: Vec<String>,
    pub consumer_name: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
    pub last_heartbeat_at: __sdk::Timestamp,
}

impl __sdk::InModule for AgentRegistry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentRegistry`.
///
/// Provides typed access to columns for query building.
pub struct AgentRegistryCols {
    pub agent_id: __sdk::__query_builder::Col<AgentRegistry, String>,
    pub namespace: __sdk::__query_builder::Col<AgentRegistry, String>,
    pub display_name: __sdk::__query_builder::Col<AgentRegistry, String>,
    pub actor_kind: __sdk::__query_builder::Col<AgentRegistry, String>,
    pub role_class: __sdk::__query_builder::Col<AgentRegistry, String>,
    pub status: __sdk::__query_builder::Col<AgentRegistry, String>,
    pub capabilities: __sdk::__query_builder::Col<AgentRegistry, Vec<String>>,
    pub consumer_name: __sdk::__query_builder::Col<AgentRegistry, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<AgentRegistry, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<AgentRegistry, __sdk::Timestamp>,
    pub last_heartbeat_at: __sdk::__query_builder::Col<AgentRegistry, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AgentRegistry {
    type Cols = AgentRegistryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentRegistryCols {
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            actor_kind: __sdk::__query_builder::Col::new(table_name, "actor_kind"),
            role_class: __sdk::__query_builder::Col::new(table_name, "role_class"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            capabilities: __sdk::__query_builder::Col::new(table_name, "capabilities"),
            consumer_name: __sdk::__query_builder::Col::new(table_name, "consumer_name"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            last_heartbeat_at: __sdk::__query_builder::Col::new(table_name, "last_heartbeat_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentRegistry`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentRegistryIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<AgentRegistry, String>,
    pub namespace: __sdk::__query_builder::IxCol<AgentRegistry, String>,
}

impl __sdk::__query_builder::HasIxCols for AgentRegistry {
    type IxCols = AgentRegistryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentRegistryIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentRegistry {}
