// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_registry_type::AgentRegistry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_registry`.
///
/// Obtain a handle from the [`AgentRegistryTableAccess::agent_registry`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_registry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_registry().on_insert(...)`.
pub struct AgentRegistryTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentRegistry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_registry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentRegistryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentRegistryTableHandle`], which mediates access to the table `agent_registry`.
    fn agent_registry(&self) -> AgentRegistryTableHandle<'_>;
}

impl AgentRegistryTableAccess for super::RemoteTables {
    fn agent_registry(&self) -> AgentRegistryTableHandle<'_> {
        AgentRegistryTableHandle {
            imp: self.imp.get_table::<AgentRegistry>("agent_registry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentRegistryInsertCallbackId(__sdk::CallbackId);
pub struct AgentRegistryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentRegistryTableHandle<'ctx> {
    type Row = AgentRegistry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentRegistry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentRegistryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentRegistryInsertCallbackId {
        AgentRegistryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentRegistryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentRegistryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentRegistryDeleteCallbackId {
        AgentRegistryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentRegistryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentRegistryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentRegistryTableHandle<'ctx> {
    type UpdateCallbackId = AgentRegistryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentRegistryUpdateCallbackId {
        AgentRegistryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentRegistryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `agent_registry`,
/// which allows point queries on the field of the same name
/// via the [`AgentRegistryAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_registry().agent_id().find(...)`.
pub struct AgentRegistryAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentRegistry, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentRegistryTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `agent_registry`.
    pub fn agent_id(&self) -> AgentRegistryAgentIdUnique<'ctx> {
        AgentRegistryAgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentRegistryAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgentRegistry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentRegistry>("agent_registry");
    _table.add_unique_constraint::<String>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentRegistry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentRegistry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentRegistry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_registryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentRegistry`.
    fn agent_registry(&self) -> __sdk::__query_builder::Table<AgentRegistry>;
}

impl agent_registryQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_registry(&self) -> __sdk::__query_builder::Table<AgentRegistry> {
        __sdk::__query_builder::Table::new("agent_registry")
    }
}
