// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BuoyEdge {
    pub key: String,
    pub namespace: String,
    pub from_agent: String,
    pub to_agent: String,
    pub subject: String,
    pub matched_text: String,
    pub weight: f32,
    pub evidence_count: u32,
    pub created_at: __sdk::Timestamp,
    pub last_reinforced: __sdk::Timestamp,
}

impl __sdk::InModule for BuoyEdge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BuoyEdge`.
///
/// Provides typed access to columns for query building.
pub struct BuoyEdgeCols {
    pub key: __sdk::__query_builder::Col<BuoyEdge, String>,
    pub namespace: __sdk::__query_builder::Col<BuoyEdge, String>,
    pub from_agent: __sdk::__query_builder::Col<BuoyEdge, String>,
    pub to_agent: __sdk::__query_builder::Col<BuoyEdge, String>,
    pub subject: __sdk::__query_builder::Col<BuoyEdge, String>,
    pub matched_text: __sdk::__query_builder::Col<BuoyEdge, String>,
    pub weight: __sdk::__query_builder::Col<BuoyEdge, f32>,
    pub evidence_count: __sdk::__query_builder::Col<BuoyEdge, u32>,
    pub created_at: __sdk::__query_builder::Col<BuoyEdge, __sdk::Timestamp>,
    pub last_reinforced: __sdk::__query_builder::Col<BuoyEdge, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BuoyEdge {
    type Cols = BuoyEdgeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuoyEdgeCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            from_agent: __sdk::__query_builder::Col::new(table_name, "from_agent"),
            to_agent: __sdk::__query_builder::Col::new(table_name, "to_agent"),
            subject: __sdk::__query_builder::Col::new(table_name, "subject"),
            matched_text: __sdk::__query_builder::Col::new(table_name, "matched_text"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            evidence_count: __sdk::__query_builder::Col::new(table_name, "evidence_count"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_reinforced: __sdk::__query_builder::Col::new(table_name, "last_reinforced"),
        }
    }
}

/// Indexed column accessor struct for the table `BuoyEdge`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuoyEdgeIxCols {
    pub from_agent: __sdk::__query_builder::IxCol<BuoyEdge, String>,
    pub key: __sdk::__query_builder::IxCol<BuoyEdge, String>,
    pub namespace: __sdk::__query_builder::IxCol<BuoyEdge, String>,
    pub to_agent: __sdk::__query_builder::IxCol<BuoyEdge, String>,
}

impl __sdk::__query_builder::HasIxCols for BuoyEdge {
    type IxCols = BuoyEdgeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuoyEdgeIxCols {
            from_agent: __sdk::__query_builder::IxCol::new(table_name, "from_agent"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
            to_agent: __sdk::__query_builder::IxCol::new(table_name, "to_agent"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BuoyEdge {}
