// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::buoy_edge_type::BuoyEdge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `buoy_edge`.
///
/// Obtain a handle from the [`BuoyEdgeTableAccess::buoy_edge`] method on [`super::RemoteTables`],
/// like `ctx.db.buoy_edge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.buoy_edge().on_insert(...)`.
pub struct BuoyEdgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<BuoyEdge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `buoy_edge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BuoyEdgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BuoyEdgeTableHandle`], which mediates access to the table `buoy_edge`.
    fn buoy_edge(&self) -> BuoyEdgeTableHandle<'_>;
}

impl BuoyEdgeTableAccess for super::RemoteTables {
    fn buoy_edge(&self) -> BuoyEdgeTableHandle<'_> {
        BuoyEdgeTableHandle {
            imp: self.imp.get_table::<BuoyEdge>("buoy_edge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BuoyEdgeInsertCallbackId(__sdk::CallbackId);
pub struct BuoyEdgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BuoyEdgeTableHandle<'ctx> {
    type Row = BuoyEdge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BuoyEdge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BuoyEdgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuoyEdgeInsertCallbackId {
        BuoyEdgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BuoyEdgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BuoyEdgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuoyEdgeDeleteCallbackId {
        BuoyEdgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BuoyEdgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BuoyEdgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BuoyEdgeTableHandle<'ctx> {
    type UpdateCallbackId = BuoyEdgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BuoyEdgeUpdateCallbackId {
        BuoyEdgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BuoyEdgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `buoy_edge`,
/// which allows point queries on the field of the same name
/// via the [`BuoyEdgeKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.buoy_edge().key().find(...)`.
pub struct BuoyEdgeKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BuoyEdge, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BuoyEdgeTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `buoy_edge`.
    pub fn key(&self) -> BuoyEdgeKeyUnique<'ctx> {
        BuoyEdgeKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BuoyEdgeKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<BuoyEdge> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BuoyEdge>("buoy_edge");
    _table.add_unique_constraint::<String>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BuoyEdge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BuoyEdge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BuoyEdge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait buoy_edgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BuoyEdge`.
    fn buoy_edge(&self) -> __sdk::__query_builder::Table<BuoyEdge>;
}

impl buoy_edgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn buoy_edge(&self) -> __sdk::__query_builder::Table<BuoyEdge> {
        __sdk::__query_builder::Table::new("buoy_edge")
    }
}
