// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BuoyListing {
    pub agent_id: String,
    pub namespace: String,
    pub display_name: String,
    pub capabilities: Vec<String>,
    pub needs: Vec<String>,
    pub offerings: Vec<String>,
    pub witness_hash: Option<String>,
    pub attractor_score: f32,
    pub visits: u32,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for BuoyListing {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BuoyListing`.
///
/// Provides typed access to columns for query building.
pub struct BuoyListingCols {
    pub agent_id: __sdk::__query_builder::Col<BuoyListing, String>,
    pub namespace: __sdk::__query_builder::Col<BuoyListing, String>,
    pub display_name: __sdk::__query_builder::Col<BuoyListing, String>,
    pub capabilities: __sdk::__query_builder::Col<BuoyListing, Vec<String>>,
    pub needs: __sdk::__query_builder::Col<BuoyListing, Vec<String>>,
    pub offerings: __sdk::__query_builder::Col<BuoyListing, Vec<String>>,
    pub witness_hash: __sdk::__query_builder::Col<BuoyListing, Option<String>>,
    pub attractor_score: __sdk::__query_builder::Col<BuoyListing, f32>,
    pub visits: __sdk::__query_builder::Col<BuoyListing, u32>,
    pub created_at: __sdk::__query_builder::Col<BuoyListing, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<BuoyListing, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for BuoyListing {
    type Cols = BuoyListingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuoyListingCols {
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            capabilities: __sdk::__query_builder::Col::new(table_name, "capabilities"),
            needs: __sdk::__query_builder::Col::new(table_name, "needs"),
            offerings: __sdk::__query_builder::Col::new(table_name, "offerings"),
            witness_hash: __sdk::__query_builder::Col::new(table_name, "witness_hash"),
            attractor_score: __sdk::__query_builder::Col::new(table_name, "attractor_score"),
            visits: __sdk::__query_builder::Col::new(table_name, "visits"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `BuoyListing`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuoyListingIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<BuoyListing, String>,
    pub namespace: __sdk::__query_builder::IxCol<BuoyListing, String>,
}

impl __sdk::__query_builder::HasIxCols for BuoyListing {
    type IxCols = BuoyListingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuoyListingIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BuoyListing {}
