// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::buoy_listing_type::BuoyListing;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `buoy_listing`.
///
/// Obtain a handle from the [`BuoyListingTableAccess::buoy_listing`] method on [`super::RemoteTables`],
/// like `ctx.db.buoy_listing()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.buoy_listing().on_insert(...)`.
pub struct BuoyListingTableHandle<'ctx> {
    imp: __sdk::TableHandle<BuoyListing>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `buoy_listing`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BuoyListingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BuoyListingTableHandle`], which mediates access to the table `buoy_listing`.
    fn buoy_listing(&self) -> BuoyListingTableHandle<'_>;
}

impl BuoyListingTableAccess for super::RemoteTables {
    fn buoy_listing(&self) -> BuoyListingTableHandle<'_> {
        BuoyListingTableHandle {
            imp: self.imp.get_table::<BuoyListing>("buoy_listing"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BuoyListingInsertCallbackId(__sdk::CallbackId);
pub struct BuoyListingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BuoyListingTableHandle<'ctx> {
    type Row = BuoyListing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BuoyListing> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BuoyListingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuoyListingInsertCallbackId {
        BuoyListingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BuoyListingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BuoyListingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuoyListingDeleteCallbackId {
        BuoyListingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BuoyListingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct BuoyListingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BuoyListingTableHandle<'ctx> {
    type UpdateCallbackId = BuoyListingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BuoyListingUpdateCallbackId {
        BuoyListingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BuoyListingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `buoy_listing`,
/// which allows point queries on the field of the same name
/// via the [`BuoyListingAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.buoy_listing().agent_id().find(...)`.
pub struct BuoyListingAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BuoyListing, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BuoyListingTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `buoy_listing`.
    pub fn agent_id(&self) -> BuoyListingAgentIdUnique<'ctx> {
        BuoyListingAgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BuoyListingAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<BuoyListing> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BuoyListing>("buoy_listing");
    _table.add_unique_constraint::<String>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BuoyListing>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BuoyListing>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BuoyListing`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait buoy_listingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BuoyListing`.
    fn buoy_listing(&self) -> __sdk::__query_builder::Table<BuoyListing>;
}

impl buoy_listingQueryTableAccess for __sdk::QueryTableAccessor {
    fn buoy_listing(&self) -> __sdk::__query_builder::Table<BuoyListing> {
        __sdk::__query_builder::Table::new("buoy_listing")
    }
}
