// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClaudeSession {
    pub session_id: String,
    pub project_path: String,
    pub project_namespace: String,
    pub transcript_path: Option<String>,
    pub model_id: Option<String>,
    pub parent_session_id: Option<String>,
    pub zellij_session: Option<String>,
    pub zellij_pane_id: Option<String>,
    pub started_at: __sdk::Timestamp,
    pub ended_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for ClaudeSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClaudeSession`.
///
/// Provides typed access to columns for query building.
pub struct ClaudeSessionCols {
    pub session_id: __sdk::__query_builder::Col<ClaudeSession, String>,
    pub project_path: __sdk::__query_builder::Col<ClaudeSession, String>,
    pub project_namespace: __sdk::__query_builder::Col<ClaudeSession, String>,
    pub transcript_path: __sdk::__query_builder::Col<ClaudeSession, Option<String>>,
    pub model_id: __sdk::__query_builder::Col<ClaudeSession, Option<String>>,
    pub parent_session_id: __sdk::__query_builder::Col<ClaudeSession, Option<String>>,
    pub zellij_session: __sdk::__query_builder::Col<ClaudeSession, Option<String>>,
    pub zellij_pane_id: __sdk::__query_builder::Col<ClaudeSession, Option<String>>,
    pub started_at: __sdk::__query_builder::Col<ClaudeSession, __sdk::Timestamp>,
    pub ended_at: __sdk::__query_builder::Col<ClaudeSession, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for ClaudeSession {
    type Cols = ClaudeSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClaudeSessionCols {
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            project_path: __sdk::__query_builder::Col::new(table_name, "project_path"),
            project_namespace: __sdk::__query_builder::Col::new(table_name, "project_namespace"),
            transcript_path: __sdk::__query_builder::Col::new(table_name, "transcript_path"),
            model_id: __sdk::__query_builder::Col::new(table_name, "model_id"),
            parent_session_id: __sdk::__query_builder::Col::new(table_name, "parent_session_id"),
            zellij_session: __sdk::__query_builder::Col::new(table_name, "zellij_session"),
            zellij_pane_id: __sdk::__query_builder::Col::new(table_name, "zellij_pane_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            ended_at: __sdk::__query_builder::Col::new(table_name, "ended_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ClaudeSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClaudeSessionIxCols {
    pub project_namespace: __sdk::__query_builder::IxCol<ClaudeSession, String>,
    pub session_id: __sdk::__query_builder::IxCol<ClaudeSession, String>,
}

impl __sdk::__query_builder::HasIxCols for ClaudeSession {
    type IxCols = ClaudeSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClaudeSessionIxCols {
            project_namespace: __sdk::__query_builder::IxCol::new(table_name, "project_namespace"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClaudeSession {}
