// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::claude_session_type::ClaudeSession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `claude_session`.
///
/// Obtain a handle from the [`ClaudeSessionTableAccess::claude_session`] method on [`super::RemoteTables`],
/// like `ctx.db.claude_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claude_session().on_insert(...)`.
pub struct ClaudeSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClaudeSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `claude_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClaudeSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClaudeSessionTableHandle`], which mediates access to the table `claude_session`.
    fn claude_session(&self) -> ClaudeSessionTableHandle<'_>;
}

impl ClaudeSessionTableAccess for super::RemoteTables {
    fn claude_session(&self) -> ClaudeSessionTableHandle<'_> {
        ClaudeSessionTableHandle {
            imp: self.imp.get_table::<ClaudeSession>("claude_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClaudeSessionInsertCallbackId(__sdk::CallbackId);
pub struct ClaudeSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClaudeSessionTableHandle<'ctx> {
    type Row = ClaudeSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClaudeSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClaudeSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaudeSessionInsertCallbackId {
        ClaudeSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClaudeSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClaudeSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClaudeSessionDeleteCallbackId {
        ClaudeSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClaudeSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClaudeSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClaudeSessionTableHandle<'ctx> {
    type UpdateCallbackId = ClaudeSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClaudeSessionUpdateCallbackId {
        ClaudeSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClaudeSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `session_id` unique index on the table `claude_session`,
/// which allows point queries on the field of the same name
/// via the [`ClaudeSessionSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.claude_session().session_id().find(...)`.
pub struct ClaudeSessionSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClaudeSession, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClaudeSessionTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `claude_session`.
    pub fn session_id(&self) -> ClaudeSessionSessionIdUnique<'ctx> {
        ClaudeSessionSessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClaudeSessionSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ClaudeSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClaudeSession>("claude_session");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClaudeSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClaudeSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClaudeSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait claude_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClaudeSession`.
    fn claude_session(&self) -> __sdk::__query_builder::Table<ClaudeSession>;
}

impl claude_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn claude_session(&self) -> __sdk::__query_builder::Table<ClaudeSession> {
        __sdk::__query_builder::Table::new("claude_session")
    }
}
