// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CleanupTestNamespaceArgs {
    pub namespace: String,
    pub confirm: String,
}

impl From<CleanupTestNamespaceArgs> for super::Reducer {
    fn from(args: CleanupTestNamespaceArgs) -> Self {
        Self::CleanupTestNamespace {
            namespace: args.namespace,
            confirm: args.confirm,
        }
    }
}

impl __sdk::InModule for CleanupTestNamespaceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cleanup_test_namespace`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cleanup_test_namespace {
    /// Request that the remote module invoke the reducer `cleanup_test_namespace` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cleanup_test_namespace:cleanup_test_namespace_then`] to run a callback after the reducer completes.
    fn cleanup_test_namespace(&self, namespace: String, confirm: String) -> __sdk::Result<()> {
        self.cleanup_test_namespace_then(namespace, confirm, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cleanup_test_namespace` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cleanup_test_namespace_then(
        &self,
        namespace: String,
        confirm: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl cleanup_test_namespace for super::RemoteReducers {
    fn cleanup_test_namespace_then(
        &self,
        namespace: String,
        confirm: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CleanupTestNamespaceArgs { namespace, confirm }, callback)
    }
}
