// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ConsumptionEvent {
    pub id: u64,
    pub memory_id: u64,
    pub consumer_name: String,
    pub ts: __sdk::Timestamp,
}

impl __sdk::InModule for ConsumptionEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ConsumptionEvent`.
///
/// Provides typed access to columns for query building.
pub struct ConsumptionEventCols {
    pub id: __sdk::__query_builder::Col<ConsumptionEvent, u64>,
    pub memory_id: __sdk::__query_builder::Col<ConsumptionEvent, u64>,
    pub consumer_name: __sdk::__query_builder::Col<ConsumptionEvent, String>,
    pub ts: __sdk::__query_builder::Col<ConsumptionEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ConsumptionEvent {
    type Cols = ConsumptionEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConsumptionEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            memory_id: __sdk::__query_builder::Col::new(table_name, "memory_id"),
            consumer_name: __sdk::__query_builder::Col::new(table_name, "consumer_name"),
            ts: __sdk::__query_builder::Col::new(table_name, "ts"),
        }
    }
}

/// Indexed column accessor struct for the table `ConsumptionEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConsumptionEventIxCols {
    pub id: __sdk::__query_builder::IxCol<ConsumptionEvent, u64>,
    pub memory_id: __sdk::__query_builder::IxCol<ConsumptionEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for ConsumptionEvent {
    type IxCols = ConsumptionEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConsumptionEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            memory_id: __sdk::__query_builder::IxCol::new(table_name, "memory_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ConsumptionEvent {}
