// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::consumption_event_type::ConsumptionEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `consumption_event`.
///
/// Obtain a handle from the [`ConsumptionEventTableAccess::consumption_event`] method on [`super::RemoteTables`],
/// like `ctx.db.consumption_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consumption_event().on_insert(...)`.
pub struct ConsumptionEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConsumptionEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `consumption_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConsumptionEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConsumptionEventTableHandle`], which mediates access to the table `consumption_event`.
    fn consumption_event(&self) -> ConsumptionEventTableHandle<'_>;
}

impl ConsumptionEventTableAccess for super::RemoteTables {
    fn consumption_event(&self) -> ConsumptionEventTableHandle<'_> {
        ConsumptionEventTableHandle {
            imp: self.imp.get_table::<ConsumptionEvent>("consumption_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConsumptionEventInsertCallbackId(__sdk::CallbackId);
pub struct ConsumptionEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConsumptionEventTableHandle<'ctx> {
    type Row = ConsumptionEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConsumptionEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConsumptionEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsumptionEventInsertCallbackId {
        ConsumptionEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConsumptionEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConsumptionEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsumptionEventDeleteCallbackId {
        ConsumptionEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConsumptionEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ConsumptionEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConsumptionEventTableHandle<'ctx> {
    type UpdateCallbackId = ConsumptionEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConsumptionEventUpdateCallbackId {
        ConsumptionEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConsumptionEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `consumption_event`,
/// which allows point queries on the field of the same name
/// via the [`ConsumptionEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consumption_event().id().find(...)`.
pub struct ConsumptionEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ConsumptionEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConsumptionEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `consumption_event`.
    pub fn id(&self) -> ConsumptionEventIdUnique<'ctx> {
        ConsumptionEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConsumptionEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ConsumptionEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ConsumptionEvent>("consumption_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ConsumptionEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConsumptionEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ConsumptionEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait consumption_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ConsumptionEvent`.
    fn consumption_event(&self) -> __sdk::__query_builder::Table<ConsumptionEvent>;
}

impl consumption_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn consumption_event(&self) -> __sdk::__query_builder::Table<ConsumptionEvent> {
        __sdk::__query_builder::Table::new("consumption_event")
    }
}
