// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Consumer {
    pub name: String,
    pub namespace: String,
    pub subscribed_at: __sdk::Timestamp,
    pub last_read_at: __sdk::Timestamp,
    pub read_count_total: u64,
    pub stale: bool,
    pub transport: String,
}

impl __sdk::InModule for Consumer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Consumer`.
///
/// Provides typed access to columns for query building.
pub struct ConsumerCols {
    pub name: __sdk::__query_builder::Col<Consumer, String>,
    pub namespace: __sdk::__query_builder::Col<Consumer, String>,
    pub subscribed_at: __sdk::__query_builder::Col<Consumer, __sdk::Timestamp>,
    pub last_read_at: __sdk::__query_builder::Col<Consumer, __sdk::Timestamp>,
    pub read_count_total: __sdk::__query_builder::Col<Consumer, u64>,
    pub stale: __sdk::__query_builder::Col<Consumer, bool>,
    pub transport: __sdk::__query_builder::Col<Consumer, String>,
}

impl __sdk::__query_builder::HasCols for Consumer {
    type Cols = ConsumerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConsumerCols {
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            subscribed_at: __sdk::__query_builder::Col::new(table_name, "subscribed_at"),
            last_read_at: __sdk::__query_builder::Col::new(table_name, "last_read_at"),
            read_count_total: __sdk::__query_builder::Col::new(table_name, "read_count_total"),
            stale: __sdk::__query_builder::Col::new(table_name, "stale"),
            transport: __sdk::__query_builder::Col::new(table_name, "transport"),
        }
    }
}

/// Indexed column accessor struct for the table `Consumer`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConsumerIxCols {
    pub name: __sdk::__query_builder::IxCol<Consumer, String>,
    pub namespace: __sdk::__query_builder::IxCol<Consumer, String>,
}

impl __sdk::__query_builder::HasIxCols for Consumer {
    type IxCols = ConsumerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConsumerIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Consumer {}
