// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::consumer_type::Consumer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `consumer`.
///
/// Obtain a handle from the [`ConsumerTableAccess::consumer`] method on [`super::RemoteTables`],
/// like `ctx.db.consumer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consumer().on_insert(...)`.
pub struct ConsumerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Consumer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `consumer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConsumerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConsumerTableHandle`], which mediates access to the table `consumer`.
    fn consumer(&self) -> ConsumerTableHandle<'_>;
}

impl ConsumerTableAccess for super::RemoteTables {
    fn consumer(&self) -> ConsumerTableHandle<'_> {
        ConsumerTableHandle {
            imp: self.imp.get_table::<Consumer>("consumer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConsumerInsertCallbackId(__sdk::CallbackId);
pub struct ConsumerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConsumerTableHandle<'ctx> {
    type Row = Consumer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Consumer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConsumerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsumerInsertCallbackId {
        ConsumerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConsumerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConsumerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsumerDeleteCallbackId {
        ConsumerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConsumerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ConsumerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConsumerTableHandle<'ctx> {
    type UpdateCallbackId = ConsumerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConsumerUpdateCallbackId {
        ConsumerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConsumerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `name` unique index on the table `consumer`,
/// which allows point queries on the field of the same name
/// via the [`ConsumerNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consumer().name().find(...)`.
pub struct ConsumerNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Consumer, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConsumerTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `consumer`.
    pub fn name(&self) -> ConsumerNameUnique<'ctx> {
        ConsumerNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConsumerNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Consumer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Consumer>("consumer");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Consumer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Consumer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Consumer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait consumerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Consumer`.
    fn consumer(&self) -> __sdk::__query_builder::Table<Consumer>;
}

impl consumerQueryTableAccess for __sdk::QueryTableAccessor {
    fn consumer(&self) -> __sdk::__query_builder::Table<Consumer> {
        __sdk::__query_builder::Table::new("consumer")
    }
}
