// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CrossSubstrateRef {
    pub id: u64,
    pub memory_id: u64,
    pub substrate: String,
    pub uri: String,
    pub anchor: Option<String>,
    pub last_seen_at: __sdk::Timestamp,
}

impl __sdk::InModule for CrossSubstrateRef {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CrossSubstrateRef`.
///
/// Provides typed access to columns for query building.
pub struct CrossSubstrateRefCols {
    pub id: __sdk::__query_builder::Col<CrossSubstrateRef, u64>,
    pub memory_id: __sdk::__query_builder::Col<CrossSubstrateRef, u64>,
    pub substrate: __sdk::__query_builder::Col<CrossSubstrateRef, String>,
    pub uri: __sdk::__query_builder::Col<CrossSubstrateRef, String>,
    pub anchor: __sdk::__query_builder::Col<CrossSubstrateRef, Option<String>>,
    pub last_seen_at: __sdk::__query_builder::Col<CrossSubstrateRef, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CrossSubstrateRef {
    type Cols = CrossSubstrateRefCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CrossSubstrateRefCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            memory_id: __sdk::__query_builder::Col::new(table_name, "memory_id"),
            substrate: __sdk::__query_builder::Col::new(table_name, "substrate"),
            uri: __sdk::__query_builder::Col::new(table_name, "uri"),
            anchor: __sdk::__query_builder::Col::new(table_name, "anchor"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CrossSubstrateRef`.
///
/// Provides typed access to indexed columns for query building.
pub struct CrossSubstrateRefIxCols {
    pub id: __sdk::__query_builder::IxCol<CrossSubstrateRef, u64>,
    pub memory_id: __sdk::__query_builder::IxCol<CrossSubstrateRef, u64>,
}

impl __sdk::__query_builder::HasIxCols for CrossSubstrateRef {
    type IxCols = CrossSubstrateRefIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CrossSubstrateRefIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            memory_id: __sdk::__query_builder::IxCol::new(table_name, "memory_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CrossSubstrateRef {}
