// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cross_substrate_ref_type::CrossSubstrateRef;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cross_substrate_ref`.
///
/// Obtain a handle from the [`CrossSubstrateRefTableAccess::cross_substrate_ref`] method on [`super::RemoteTables`],
/// like `ctx.db.cross_substrate_ref()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cross_substrate_ref().on_insert(...)`.
pub struct CrossSubstrateRefTableHandle<'ctx> {
    imp: __sdk::TableHandle<CrossSubstrateRef>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cross_substrate_ref`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CrossSubstrateRefTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CrossSubstrateRefTableHandle`], which mediates access to the table `cross_substrate_ref`.
    fn cross_substrate_ref(&self) -> CrossSubstrateRefTableHandle<'_>;
}

impl CrossSubstrateRefTableAccess for super::RemoteTables {
    fn cross_substrate_ref(&self) -> CrossSubstrateRefTableHandle<'_> {
        CrossSubstrateRefTableHandle {
            imp: self
                .imp
                .get_table::<CrossSubstrateRef>("cross_substrate_ref"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CrossSubstrateRefInsertCallbackId(__sdk::CallbackId);
pub struct CrossSubstrateRefDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CrossSubstrateRefTableHandle<'ctx> {
    type Row = CrossSubstrateRef;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CrossSubstrateRef> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CrossSubstrateRefInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrossSubstrateRefInsertCallbackId {
        CrossSubstrateRefInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CrossSubstrateRefInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CrossSubstrateRefDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CrossSubstrateRefDeleteCallbackId {
        CrossSubstrateRefDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CrossSubstrateRefDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CrossSubstrateRefUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CrossSubstrateRefTableHandle<'ctx> {
    type UpdateCallbackId = CrossSubstrateRefUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CrossSubstrateRefUpdateCallbackId {
        CrossSubstrateRefUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CrossSubstrateRefUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `cross_substrate_ref`,
/// which allows point queries on the field of the same name
/// via the [`CrossSubstrateRefIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cross_substrate_ref().id().find(...)`.
pub struct CrossSubstrateRefIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CrossSubstrateRef, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CrossSubstrateRefTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `cross_substrate_ref`.
    pub fn id(&self) -> CrossSubstrateRefIdUnique<'ctx> {
        CrossSubstrateRefIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CrossSubstrateRefIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CrossSubstrateRef> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CrossSubstrateRef>("cross_substrate_ref");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CrossSubstrateRef>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CrossSubstrateRef>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CrossSubstrateRef`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cross_substrate_refQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CrossSubstrateRef`.
    fn cross_substrate_ref(&self) -> __sdk::__query_builder::Table<CrossSubstrateRef>;
}

impl cross_substrate_refQueryTableAccess for __sdk::QueryTableAccessor {
    fn cross_substrate_ref(&self) -> __sdk::__query_builder::Table<CrossSubstrateRef> {
        __sdk::__query_builder::Table::new("cross_substrate_ref")
    }
}
