// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::decay_audit_type::DecayAudit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `decay_audit`.
///
/// Obtain a handle from the [`DecayAuditTableAccess::decay_audit`] method on [`super::RemoteTables`],
/// like `ctx.db.decay_audit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.decay_audit().on_insert(...)`.
pub struct DecayAuditTableHandle<'ctx> {
    imp: __sdk::TableHandle<DecayAudit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `decay_audit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DecayAuditTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DecayAuditTableHandle`], which mediates access to the table `decay_audit`.
    fn decay_audit(&self) -> DecayAuditTableHandle<'_>;
}

impl DecayAuditTableAccess for super::RemoteTables {
    fn decay_audit(&self) -> DecayAuditTableHandle<'_> {
        DecayAuditTableHandle {
            imp: self.imp.get_table::<DecayAudit>("decay_audit"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DecayAuditInsertCallbackId(__sdk::CallbackId);
pub struct DecayAuditDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DecayAuditTableHandle<'ctx> {
    type Row = DecayAudit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DecayAudit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DecayAuditInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DecayAuditInsertCallbackId {
        DecayAuditInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DecayAuditInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DecayAuditDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DecayAuditDeleteCallbackId {
        DecayAuditDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DecayAuditDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DecayAuditUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DecayAuditTableHandle<'ctx> {
    type UpdateCallbackId = DecayAuditUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DecayAuditUpdateCallbackId {
        DecayAuditUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DecayAuditUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `decay_audit`,
/// which allows point queries on the field of the same name
/// via the [`DecayAuditIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.decay_audit().id().find(...)`.
pub struct DecayAuditIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DecayAudit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DecayAuditTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `decay_audit`.
    pub fn id(&self) -> DecayAuditIdUnique<'ctx> {
        DecayAuditIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DecayAuditIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DecayAudit> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DecayAudit>("decay_audit");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DecayAudit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DecayAudit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DecayAudit`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait decay_auditQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DecayAudit`.
    fn decay_audit(&self) -> __sdk::__query_builder::Table<DecayAudit>;
}

impl decay_auditQueryTableAccess for __sdk::QueryTableAccessor {
    fn decay_audit(&self) -> __sdk::__query_builder::Table<DecayAudit> {
        __sdk::__query_builder::Table::new("decay_audit")
    }
}
