// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DecayAudit {
    pub id: u64,
    pub tick: u64,
    pub pathways_decayed: u32,
    pub memories_pruned: u32,
    pub memories_crystallized: u32,
    pub ts: __sdk::Timestamp,
}

impl __sdk::InModule for DecayAudit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DecayAudit`.
///
/// Provides typed access to columns for query building.
pub struct DecayAuditCols {
    pub id: __sdk::__query_builder::Col<DecayAudit, u64>,
    pub tick: __sdk::__query_builder::Col<DecayAudit, u64>,
    pub pathways_decayed: __sdk::__query_builder::Col<DecayAudit, u32>,
    pub memories_pruned: __sdk::__query_builder::Col<DecayAudit, u32>,
    pub memories_crystallized: __sdk::__query_builder::Col<DecayAudit, u32>,
    pub ts: __sdk::__query_builder::Col<DecayAudit, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for DecayAudit {
    type Cols = DecayAuditCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DecayAuditCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            pathways_decayed: __sdk::__query_builder::Col::new(table_name, "pathways_decayed"),
            memories_pruned: __sdk::__query_builder::Col::new(table_name, "memories_pruned"),
            memories_crystallized: __sdk::__query_builder::Col::new(
                table_name,
                "memories_crystallized",
            ),
            ts: __sdk::__query_builder::Col::new(table_name, "ts"),
        }
    }
}

/// Indexed column accessor struct for the table `DecayAudit`.
///
/// Provides typed access to indexed columns for query building.
pub struct DecayAuditIxCols {
    pub id: __sdk::__query_builder::IxCol<DecayAudit, u64>,
}

impl __sdk::__query_builder::HasIxCols for DecayAudit {
    type IxCols = DecayAuditIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DecayAuditIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DecayAudit {}
