// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ghost_memory_type::GhostMemory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ghost_memory`.
///
/// Obtain a handle from the [`GhostMemoryTableAccess::ghost_memory`] method on [`super::RemoteTables`],
/// like `ctx.db.ghost_memory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ghost_memory().on_insert(...)`.
pub struct GhostMemoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<GhostMemory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ghost_memory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GhostMemoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GhostMemoryTableHandle`], which mediates access to the table `ghost_memory`.
    fn ghost_memory(&self) -> GhostMemoryTableHandle<'_>;
}

impl GhostMemoryTableAccess for super::RemoteTables {
    fn ghost_memory(&self) -> GhostMemoryTableHandle<'_> {
        GhostMemoryTableHandle {
            imp: self.imp.get_table::<GhostMemory>("ghost_memory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GhostMemoryInsertCallbackId(__sdk::CallbackId);
pub struct GhostMemoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GhostMemoryTableHandle<'ctx> {
    type Row = GhostMemory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GhostMemory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GhostMemoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GhostMemoryInsertCallbackId {
        GhostMemoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GhostMemoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GhostMemoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GhostMemoryDeleteCallbackId {
        GhostMemoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GhostMemoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GhostMemoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GhostMemoryTableHandle<'ctx> {
    type UpdateCallbackId = GhostMemoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GhostMemoryUpdateCallbackId {
        GhostMemoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GhostMemoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ghost_memory`,
/// which allows point queries on the field of the same name
/// via the [`GhostMemoryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ghost_memory().id().find(...)`.
pub struct GhostMemoryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GhostMemory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GhostMemoryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ghost_memory`.
    pub fn id(&self) -> GhostMemoryIdUnique<'ctx> {
        GhostMemoryIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GhostMemoryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GhostMemory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GhostMemory>("ghost_memory");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GhostMemory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GhostMemory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GhostMemory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ghost_memoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GhostMemory`.
    fn ghost_memory(&self) -> __sdk::__query_builder::Table<GhostMemory>;
}

impl ghost_memoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn ghost_memory(&self) -> __sdk::__query_builder::Table<GhostMemory> {
        __sdk::__query_builder::Table::new("ghost_memory")
    }
}
