// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GhostMemory {
    pub id: u64,
    pub original_id: u64,
    pub namespace: String,
    pub modality: String,
    pub content_preview: String,
    pub final_intensity: f32,
    pub final_access_count: u32,
    pub decayed_at: __sdk::Timestamp,
}

impl __sdk::InModule for GhostMemory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GhostMemory`.
///
/// Provides typed access to columns for query building.
pub struct GhostMemoryCols {
    pub id: __sdk::__query_builder::Col<GhostMemory, u64>,
    pub original_id: __sdk::__query_builder::Col<GhostMemory, u64>,
    pub namespace: __sdk::__query_builder::Col<GhostMemory, String>,
    pub modality: __sdk::__query_builder::Col<GhostMemory, String>,
    pub content_preview: __sdk::__query_builder::Col<GhostMemory, String>,
    pub final_intensity: __sdk::__query_builder::Col<GhostMemory, f32>,
    pub final_access_count: __sdk::__query_builder::Col<GhostMemory, u32>,
    pub decayed_at: __sdk::__query_builder::Col<GhostMemory, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GhostMemory {
    type Cols = GhostMemoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GhostMemoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            original_id: __sdk::__query_builder::Col::new(table_name, "original_id"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            modality: __sdk::__query_builder::Col::new(table_name, "modality"),
            content_preview: __sdk::__query_builder::Col::new(table_name, "content_preview"),
            final_intensity: __sdk::__query_builder::Col::new(table_name, "final_intensity"),
            final_access_count: __sdk::__query_builder::Col::new(table_name, "final_access_count"),
            decayed_at: __sdk::__query_builder::Col::new(table_name, "decayed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `GhostMemory`.
///
/// Provides typed access to indexed columns for query building.
pub struct GhostMemoryIxCols {
    pub id: __sdk::__query_builder::IxCol<GhostMemory, u64>,
}

impl __sdk::__query_builder::HasIxCols for GhostMemory {
    type IxCols = GhostMemoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GhostMemoryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GhostMemory {}
