// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HeartbeatConsumerArgs {
    pub name: String,
}

impl From<HeartbeatConsumerArgs> for super::Reducer {
    fn from(args: HeartbeatConsumerArgs) -> Self {
        Self::HeartbeatConsumer { name: args.name }
    }
}

impl __sdk::InModule for HeartbeatConsumerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `heartbeat_consumer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait heartbeat_consumer {
    /// Request that the remote module invoke the reducer `heartbeat_consumer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`heartbeat_consumer:heartbeat_consumer_then`] to run a callback after the reducer completes.
    fn heartbeat_consumer(&self, name: String) -> __sdk::Result<()> {
        self.heartbeat_consumer_then(name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `heartbeat_consumer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn heartbeat_consumer_then(
        &self,
        name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl heartbeat_consumer for super::RemoteReducers {
    fn heartbeat_consumer_then(
        &self,
        name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(HeartbeatConsumerArgs { name }, callback)
    }
}
