// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hermes_memory_context_row_type::HermesMemoryContextRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hermes_memory_context`.
///
/// Obtain a handle from the [`HermesMemoryContextTableAccess::hermes_memory_context`] method on [`super::RemoteTables`],
/// like `ctx.db.hermes_memory_context()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hermes_memory_context().on_insert(...)`.
pub struct HermesMemoryContextTableHandle<'ctx> {
    imp: __sdk::TableHandle<HermesMemoryContextRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hermes_memory_context`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HermesMemoryContextTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HermesMemoryContextTableHandle`], which mediates access to the table `hermes_memory_context`.
    fn hermes_memory_context(&self) -> HermesMemoryContextTableHandle<'_>;
}

impl HermesMemoryContextTableAccess for super::RemoteTables {
    fn hermes_memory_context(&self) -> HermesMemoryContextTableHandle<'_> {
        HermesMemoryContextTableHandle {
            imp: self
                .imp
                .get_table::<HermesMemoryContextRow>("hermes_memory_context"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HermesMemoryContextInsertCallbackId(__sdk::CallbackId);
pub struct HermesMemoryContextDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HermesMemoryContextTableHandle<'ctx> {
    type Row = HermesMemoryContextRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HermesMemoryContextRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HermesMemoryContextInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HermesMemoryContextInsertCallbackId {
        HermesMemoryContextInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HermesMemoryContextInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HermesMemoryContextDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HermesMemoryContextDeleteCallbackId {
        HermesMemoryContextDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HermesMemoryContextDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HermesMemoryContextRow>("hermes_memory_context");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HermesMemoryContextRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HermesMemoryContextRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HermesMemoryContextRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hermes_memory_contextQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HermesMemoryContextRow`.
    fn hermes_memory_context(&self) -> __sdk::__query_builder::Table<HermesMemoryContextRow>;
}

impl hermes_memory_contextQueryTableAccess for __sdk::QueryTableAccessor {
    fn hermes_memory_context(&self) -> __sdk::__query_builder::Table<HermesMemoryContextRow> {
        __sdk::__query_builder::Table::new("hermes_memory_context")
    }
}
