// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HermesMemoryContextRow {
    pub id: u64,
    pub modality: String,
    pub content_preview: String,
    pub intensity: f32,
    pub tensor_dim: Option<u32>,
    pub access_count: u32,
    pub created_at: __sdk::Timestamp,
    pub last_accessed: __sdk::Timestamp,
    pub crystallized: bool,
    pub session_id: String,
    pub instance_id: Option<String>,
}

impl __sdk::InModule for HermesMemoryContextRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HermesMemoryContextRow`.
///
/// Provides typed access to columns for query building.
pub struct HermesMemoryContextRowCols {
    pub id: __sdk::__query_builder::Col<HermesMemoryContextRow, u64>,
    pub modality: __sdk::__query_builder::Col<HermesMemoryContextRow, String>,
    pub content_preview: __sdk::__query_builder::Col<HermesMemoryContextRow, String>,
    pub intensity: __sdk::__query_builder::Col<HermesMemoryContextRow, f32>,
    pub tensor_dim: __sdk::__query_builder::Col<HermesMemoryContextRow, Option<u32>>,
    pub access_count: __sdk::__query_builder::Col<HermesMemoryContextRow, u32>,
    pub created_at: __sdk::__query_builder::Col<HermesMemoryContextRow, __sdk::Timestamp>,
    pub last_accessed: __sdk::__query_builder::Col<HermesMemoryContextRow, __sdk::Timestamp>,
    pub crystallized: __sdk::__query_builder::Col<HermesMemoryContextRow, bool>,
    pub session_id: __sdk::__query_builder::Col<HermesMemoryContextRow, String>,
    pub instance_id: __sdk::__query_builder::Col<HermesMemoryContextRow, Option<String>>,
}

impl __sdk::__query_builder::HasCols for HermesMemoryContextRow {
    type Cols = HermesMemoryContextRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HermesMemoryContextRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            modality: __sdk::__query_builder::Col::new(table_name, "modality"),
            content_preview: __sdk::__query_builder::Col::new(table_name, "content_preview"),
            intensity: __sdk::__query_builder::Col::new(table_name, "intensity"),
            tensor_dim: __sdk::__query_builder::Col::new(table_name, "tensor_dim"),
            access_count: __sdk::__query_builder::Col::new(table_name, "access_count"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_accessed: __sdk::__query_builder::Col::new(table_name, "last_accessed"),
            crystallized: __sdk::__query_builder::Col::new(table_name, "crystallized"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
        }
    }
}
