// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HermesPathwayContextRow {
    pub id: u64,
    pub pre_id: String,
    pub post_id: String,
    pub weight: f32,
    pub last_reinforced: __sdk::Timestamp,
    pub reinforce_count: u32,
    pub session_id: String,
    pub instance_id: Option<String>,
}

impl __sdk::InModule for HermesPathwayContextRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HermesPathwayContextRow`.
///
/// Provides typed access to columns for query building.
pub struct HermesPathwayContextRowCols {
    pub id: __sdk::__query_builder::Col<HermesPathwayContextRow, u64>,
    pub pre_id: __sdk::__query_builder::Col<HermesPathwayContextRow, String>,
    pub post_id: __sdk::__query_builder::Col<HermesPathwayContextRow, String>,
    pub weight: __sdk::__query_builder::Col<HermesPathwayContextRow, f32>,
    pub last_reinforced: __sdk::__query_builder::Col<HermesPathwayContextRow, __sdk::Timestamp>,
    pub reinforce_count: __sdk::__query_builder::Col<HermesPathwayContextRow, u32>,
    pub session_id: __sdk::__query_builder::Col<HermesPathwayContextRow, String>,
    pub instance_id: __sdk::__query_builder::Col<HermesPathwayContextRow, Option<String>>,
}

impl __sdk::__query_builder::HasCols for HermesPathwayContextRow {
    type Cols = HermesPathwayContextRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HermesPathwayContextRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            pre_id: __sdk::__query_builder::Col::new(table_name, "pre_id"),
            post_id: __sdk::__query_builder::Col::new(table_name, "post_id"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            last_reinforced: __sdk::__query_builder::Col::new(table_name, "last_reinforced"),
            reinforce_count: __sdk::__query_builder::Col::new(table_name, "reinforce_count"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
        }
    }
}
