// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hermes_pathway_context_row_type::HermesPathwayContextRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hermes_pathway_context`.
///
/// Obtain a handle from the [`HermesPathwayContextTableAccess::hermes_pathway_context`] method on [`super::RemoteTables`],
/// like `ctx.db.hermes_pathway_context()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hermes_pathway_context().on_insert(...)`.
pub struct HermesPathwayContextTableHandle<'ctx> {
    imp: __sdk::TableHandle<HermesPathwayContextRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hermes_pathway_context`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HermesPathwayContextTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HermesPathwayContextTableHandle`], which mediates access to the table `hermes_pathway_context`.
    fn hermes_pathway_context(&self) -> HermesPathwayContextTableHandle<'_>;
}

impl HermesPathwayContextTableAccess for super::RemoteTables {
    fn hermes_pathway_context(&self) -> HermesPathwayContextTableHandle<'_> {
        HermesPathwayContextTableHandle {
            imp: self
                .imp
                .get_table::<HermesPathwayContextRow>("hermes_pathway_context"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HermesPathwayContextInsertCallbackId(__sdk::CallbackId);
pub struct HermesPathwayContextDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HermesPathwayContextTableHandle<'ctx> {
    type Row = HermesPathwayContextRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HermesPathwayContextRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HermesPathwayContextInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HermesPathwayContextInsertCallbackId {
        HermesPathwayContextInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HermesPathwayContextInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HermesPathwayContextDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HermesPathwayContextDeleteCallbackId {
        HermesPathwayContextDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HermesPathwayContextDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<HermesPathwayContextRow>("hermes_pathway_context");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HermesPathwayContextRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HermesPathwayContextRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HermesPathwayContextRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hermes_pathway_contextQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HermesPathwayContextRow`.
    fn hermes_pathway_context(&self) -> __sdk::__query_builder::Table<HermesPathwayContextRow>;
}

impl hermes_pathway_contextQueryTableAccess for __sdk::QueryTableAccessor {
    fn hermes_pathway_context(&self) -> __sdk::__query_builder::Table<HermesPathwayContextRow> {
        __sdk::__query_builder::Table::new("hermes_pathway_context")
    }
}
