// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HydratePathwayLookupArgs {
    pub namespace: String,
    pub max_rows: u32,
}

impl From<HydratePathwayLookupArgs> for super::Reducer {
    fn from(args: HydratePathwayLookupArgs) -> Self {
        Self::HydratePathwayLookup {
            namespace: args.namespace,
            max_rows: args.max_rows,
        }
    }
}

impl __sdk::InModule for HydratePathwayLookupArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `hydrate_pathway_lookup`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait hydrate_pathway_lookup {
    /// Request that the remote module invoke the reducer `hydrate_pathway_lookup` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`hydrate_pathway_lookup:hydrate_pathway_lookup_then`] to run a callback after the reducer completes.
    fn hydrate_pathway_lookup(&self, namespace: String, max_rows: u32) -> __sdk::Result<()> {
        self.hydrate_pathway_lookup_then(namespace, max_rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `hydrate_pathway_lookup` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn hydrate_pathway_lookup_then(
        &self,
        namespace: String,
        max_rows: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl hydrate_pathway_lookup for super::RemoteReducers {
    fn hydrate_pathway_lookup_then(
        &self,
        namespace: String,
        max_rows: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            HydratePathwayLookupArgs {
                namespace,
                max_rows,
            },
            callback,
        )
    }
}
