// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Memory {
    pub id: u64,
    pub namespace: String,
    pub modality: String,
    pub content: String,
    pub intensity: f32,
    pub tensor_bytes: Option<Vec<u8>>,
    pub tensor_dim: Option<u32>,
    pub access_count: u32,
    pub created_at: __sdk::Timestamp,
    pub last_accessed: __sdk::Timestamp,
    pub crystallized: bool,
    pub session_id: String,
    pub instance_id: Option<String>,
    pub parent_ids: Vec<u64>,
}

impl __sdk::InModule for Memory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Memory`.
///
/// Provides typed access to columns for query building.
pub struct MemoryCols {
    pub id: __sdk::__query_builder::Col<Memory, u64>,
    pub namespace: __sdk::__query_builder::Col<Memory, String>,
    pub modality: __sdk::__query_builder::Col<Memory, String>,
    pub content: __sdk::__query_builder::Col<Memory, String>,
    pub intensity: __sdk::__query_builder::Col<Memory, f32>,
    pub tensor_bytes: __sdk::__query_builder::Col<Memory, Option<Vec<u8>>>,
    pub tensor_dim: __sdk::__query_builder::Col<Memory, Option<u32>>,
    pub access_count: __sdk::__query_builder::Col<Memory, u32>,
    pub created_at: __sdk::__query_builder::Col<Memory, __sdk::Timestamp>,
    pub last_accessed: __sdk::__query_builder::Col<Memory, __sdk::Timestamp>,
    pub crystallized: __sdk::__query_builder::Col<Memory, bool>,
    pub session_id: __sdk::__query_builder::Col<Memory, String>,
    pub instance_id: __sdk::__query_builder::Col<Memory, Option<String>>,
    pub parent_ids: __sdk::__query_builder::Col<Memory, Vec<u64>>,
}

impl __sdk::__query_builder::HasCols for Memory {
    type Cols = MemoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MemoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            modality: __sdk::__query_builder::Col::new(table_name, "modality"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            intensity: __sdk::__query_builder::Col::new(table_name, "intensity"),
            tensor_bytes: __sdk::__query_builder::Col::new(table_name, "tensor_bytes"),
            tensor_dim: __sdk::__query_builder::Col::new(table_name, "tensor_dim"),
            access_count: __sdk::__query_builder::Col::new(table_name, "access_count"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_accessed: __sdk::__query_builder::Col::new(table_name, "last_accessed"),
            crystallized: __sdk::__query_builder::Col::new(table_name, "crystallized"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            parent_ids: __sdk::__query_builder::Col::new(table_name, "parent_ids"),
        }
    }
}

/// Indexed column accessor struct for the table `Memory`.
///
/// Provides typed access to indexed columns for query building.
pub struct MemoryIxCols {
    pub id: __sdk::__query_builder::IxCol<Memory, u64>,
    pub namespace: __sdk::__query_builder::IxCol<Memory, String>,
}

impl __sdk::__query_builder::HasIxCols for Memory {
    type IxCols = MemoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MemoryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Memory {}
