// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::memory_type::Memory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `memory`.
///
/// Obtain a handle from the [`MemoryTableAccess::memory`] method on [`super::RemoteTables`],
/// like `ctx.db.memory()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.memory().on_insert(...)`.
pub struct MemoryTableHandle<'ctx> {
    imp: __sdk::TableHandle<Memory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `memory`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MemoryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MemoryTableHandle`], which mediates access to the table `memory`.
    fn memory(&self) -> MemoryTableHandle<'_>;
}

impl MemoryTableAccess for super::RemoteTables {
    fn memory(&self) -> MemoryTableHandle<'_> {
        MemoryTableHandle {
            imp: self.imp.get_table::<Memory>("memory"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MemoryInsertCallbackId(__sdk::CallbackId);
pub struct MemoryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MemoryTableHandle<'ctx> {
    type Row = Memory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Memory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MemoryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MemoryInsertCallbackId {
        MemoryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MemoryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MemoryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MemoryDeleteCallbackId {
        MemoryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MemoryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MemoryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MemoryTableHandle<'ctx> {
    type UpdateCallbackId = MemoryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MemoryUpdateCallbackId {
        MemoryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MemoryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `memory`,
/// which allows point queries on the field of the same name
/// via the [`MemoryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.memory().id().find(...)`.
pub struct MemoryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Memory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MemoryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `memory`.
    pub fn id(&self) -> MemoryIdUnique<'ctx> {
        MemoryIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MemoryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Memory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Memory>("memory");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Memory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Memory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Memory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait memoryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Memory`.
    fn memory(&self) -> __sdk::__query_builder::Table<Memory>;
}

impl memoryQueryTableAccess for __sdk::QueryTableAccessor {
    fn memory(&self) -> __sdk::__query_builder::Table<Memory> {
        __sdk::__query_builder::Table::new("memory")
    }
}
