// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit fbec2761abbf65b90673130835c4cab6c016924c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod access_memory_reducer;
pub mod add_cross_substrate_ref_reducer;
pub mod agent_registry_table;
pub mod agent_registry_type;
pub mod buoy_edge_table;
pub mod buoy_edge_type;
pub mod buoy_listing_table;
pub mod buoy_listing_type;
pub mod claude_session_table;
pub mod claude_session_type;
pub mod cleanup_test_namespace_reducer;
pub mod consumer_table;
pub mod consumer_type;
pub mod consumption_event_table;
pub mod consumption_event_type;
pub mod cross_substrate_ref_table;
pub mod cross_substrate_ref_type;
pub mod decay_audit_table;
pub mod decay_audit_type;
pub mod decay_schedule_type;
pub mod end_claude_session_reducer;
pub mod ghost_memory_table;
pub mod ghost_memory_type;
pub mod heartbeat_consumer_reducer;
pub mod hermes_memory_context_row_type;
pub mod hermes_memory_context_table;
pub mod hermes_pathway_context_row_type;
pub mod hermes_pathway_context_table;
pub mod hydrate_pathway_lookup_reducer;
pub mod memory_table;
pub mod memory_type;
pub mod nearest_neighbor_reducer;
pub mod nn_result_table;
pub mod nn_result_type;
pub mod pane_context_table;
pub mod pane_context_type;
pub mod pathway_lookup_type;
pub mod pathway_table;
pub mod pathway_type;
pub mod purge_nn_result_similarity_anomalies_reducer;
pub mod record_buoy_exchange_v_1_reducer;
pub mod record_tool_invocation_reducer;
pub mod register_claude_session_reducer;
pub mod register_consumer_reducer;
pub mod reinforce_pathway_reducer;
pub mod revoke_buoy_agent_v_1_reducer;
pub mod suspend_buoy_agent_v_1_reducer;
pub mod tick_counter_type;
pub mod tool_invocation_table;
pub mod tool_invocation_type;
pub mod unregister_consumer_reducer;
pub mod visit_buoy_v_1_reducer;
pub mod write_memory_reducer;
pub mod write_pathway_reducer;

pub use access_memory_reducer::access_memory;
pub use add_cross_substrate_ref_reducer::add_cross_substrate_ref;
pub use agent_registry_table::*;
pub use agent_registry_type::AgentRegistry;
pub use buoy_edge_table::*;
pub use buoy_edge_type::BuoyEdge;
pub use buoy_listing_table::*;
pub use buoy_listing_type::BuoyListing;
pub use claude_session_table::*;
pub use claude_session_type::ClaudeSession;
pub use cleanup_test_namespace_reducer::cleanup_test_namespace;
pub use consumer_table::*;
pub use consumer_type::Consumer;
pub use consumption_event_table::*;
pub use consumption_event_type::ConsumptionEvent;
pub use cross_substrate_ref_table::*;
pub use cross_substrate_ref_type::CrossSubstrateRef;
pub use decay_audit_table::*;
pub use decay_audit_type::DecayAudit;
pub use decay_schedule_type::DecaySchedule;
pub use end_claude_session_reducer::end_claude_session;
pub use ghost_memory_table::*;
pub use ghost_memory_type::GhostMemory;
pub use heartbeat_consumer_reducer::heartbeat_consumer;
pub use hermes_memory_context_row_type::HermesMemoryContextRow;
pub use hermes_memory_context_table::*;
pub use hermes_pathway_context_row_type::HermesPathwayContextRow;
pub use hermes_pathway_context_table::*;
pub use hydrate_pathway_lookup_reducer::hydrate_pathway_lookup;
pub use memory_table::*;
pub use memory_type::Memory;
pub use nearest_neighbor_reducer::nearest_neighbor;
pub use nn_result_table::*;
pub use nn_result_type::NnResult;
pub use pane_context_table::*;
pub use pane_context_type::PaneContext;
pub use pathway_lookup_type::PathwayLookup;
pub use pathway_table::*;
pub use pathway_type::Pathway;
pub use purge_nn_result_similarity_anomalies_reducer::purge_nn_result_similarity_anomalies;
pub use record_buoy_exchange_v_1_reducer::record_buoy_exchange_v_1;
pub use record_tool_invocation_reducer::record_tool_invocation;
pub use register_claude_session_reducer::register_claude_session;
pub use register_consumer_reducer::register_consumer;
pub use reinforce_pathway_reducer::reinforce_pathway;
pub use revoke_buoy_agent_v_1_reducer::revoke_buoy_agent_v_1;
pub use suspend_buoy_agent_v_1_reducer::suspend_buoy_agent_v_1;
pub use tick_counter_type::TickCounter;
pub use tool_invocation_table::*;
pub use tool_invocation_type::ToolInvocation;
pub use unregister_consumer_reducer::unregister_consumer;
pub use visit_buoy_v_1_reducer::visit_buoy_v_1;
pub use write_memory_reducer::write_memory;
pub use write_pathway_reducer::write_pathway;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AccessMemory {
        memory_id: u64,
        consumer_name: String,
    },
    AddCrossSubstrateRef {
        memory_id: u64,
        substrate: String,
        uri: String,
        anchor: Option<String>,
    },
    CleanupTestNamespace {
        namespace: String,
        confirm: String,
    },
    EndClaudeSession {
        session_id: String,
    },
    HeartbeatConsumer {
        name: String,
    },
    HydratePathwayLookup {
        namespace: String,
        max_rows: u32,
    },
    NearestNeighbor {
        query_id: String,
        query: Vec<f32>,
        k: u32,
        namespace: String,
    },
    PurgeNnResultSimilarityAnomalies {
        confirm: String,
    },
    RecordBuoyExchangeV1 {
        namespace: String,
        from_agent: String,
        to_agent: String,
        subject: String,
        evidence_hash: String,
        verified: bool,
    },
    RecordToolInvocation {
        session_id: String,
        tool_name: String,
        args_hash: String,
        args_summary: Option<String>,
        success: bool,
        duration_ms: Option<u64>,
    },
    RegisterClaudeSession {
        session_id: String,
        project_path: String,
        project_namespace: String,
        transcript_path: Option<String>,
        model_id: Option<String>,
        parent_session_id: Option<String>,
        zellij_session: Option<String>,
        zellij_pane_id: Option<String>,
    },
    RegisterConsumer {
        name: String,
        namespace: String,
        transport: String,
    },
    ReinforcePathway {
        pre_id: String,
        post_id: String,
        namespace: String,
        delta: f32,
    },
    RevokeBuoyAgentV1 {
        agent_id: String,
        reason: String,
    },
    SuspendBuoyAgentV1 {
        agent_id: String,
        reason: String,
    },
    UnregisterConsumer {
        name: String,
    },
    VisitBuoyV1 {
        namespace: String,
        agent_id: String,
        display_name: String,
        capabilities: Vec<String>,
        needs: Vec<String>,
        offerings: Vec<String>,
        witness_hash: Option<String>,
        consumer_name: Option<String>,
    },
    WriteMemory {
        namespace: String,
        modality: String,
        content: String,
        intensity: f32,
        tensor: Option<Vec<f32>>,
        session_id: String,
        instance_id: Option<String>,
        parent_ids: Vec<u64>,
    },
    WritePathway {
        pre_id: String,
        post_id: String,
        namespace: String,
        weight: f32,
        session_id: String,
        instance_id: Option<String>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AccessMemory { .. } => "access_memory",
            Reducer::AddCrossSubstrateRef { .. } => "add_cross_substrate_ref",
            Reducer::CleanupTestNamespace { .. } => "cleanup_test_namespace",
            Reducer::EndClaudeSession { .. } => "end_claude_session",
            Reducer::HeartbeatConsumer { .. } => "heartbeat_consumer",
            Reducer::HydratePathwayLookup { .. } => "hydrate_pathway_lookup",
            Reducer::NearestNeighbor { .. } => "nearest_neighbor",
            Reducer::PurgeNnResultSimilarityAnomalies { .. } => {
                "purge_nn_result_similarity_anomalies"
            }
            Reducer::RecordBuoyExchangeV1 { .. } => "record_buoy_exchange_v_1",
            Reducer::RecordToolInvocation { .. } => "record_tool_invocation",
            Reducer::RegisterClaudeSession { .. } => "register_claude_session",
            Reducer::RegisterConsumer { .. } => "register_consumer",
            Reducer::ReinforcePathway { .. } => "reinforce_pathway",
            Reducer::RevokeBuoyAgentV1 { .. } => "revoke_buoy_agent_v_1",
            Reducer::SuspendBuoyAgentV1 { .. } => "suspend_buoy_agent_v_1",
            Reducer::UnregisterConsumer { .. } => "unregister_consumer",
            Reducer::VisitBuoyV1 { .. } => "visit_buoy_v_1",
            Reducer::WriteMemory { .. } => "write_memory",
            Reducer::WritePathway { .. } => "write_pathway",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AccessMemory{
                memory_id,
                consumer_name,
}             => __sats::bsatn::to_vec(&access_memory_reducer::AccessMemoryArgs {
                memory_id: memory_id.clone(),
                consumer_name: consumer_name.clone(),
}),
            Reducer::AddCrossSubstrateRef{
                memory_id,
                substrate,
                uri,
                anchor,
}             => __sats::bsatn::to_vec(&add_cross_substrate_ref_reducer::AddCrossSubstrateRefArgs {
                memory_id: memory_id.clone(),
                substrate: substrate.clone(),
                uri: uri.clone(),
                anchor: anchor.clone(),
}),
            Reducer::CleanupTestNamespace{
                namespace,
                confirm,
}             => __sats::bsatn::to_vec(&cleanup_test_namespace_reducer::CleanupTestNamespaceArgs {
                namespace: namespace.clone(),
                confirm: confirm.clone(),
}),
            Reducer::EndClaudeSession{
                session_id,
}             => __sats::bsatn::to_vec(&end_claude_session_reducer::EndClaudeSessionArgs {
                session_id: session_id.clone(),
}),
            Reducer::HeartbeatConsumer{
                name,
}             => __sats::bsatn::to_vec(&heartbeat_consumer_reducer::HeartbeatConsumerArgs {
                name: name.clone(),
}),
            Reducer::HydratePathwayLookup{
                namespace,
                max_rows,
}             => __sats::bsatn::to_vec(&hydrate_pathway_lookup_reducer::HydratePathwayLookupArgs {
                namespace: namespace.clone(),
                max_rows: max_rows.clone(),
}),
            Reducer::NearestNeighbor{
                query_id,
                query,
                k,
                namespace,
}             => __sats::bsatn::to_vec(&nearest_neighbor_reducer::NearestNeighborArgs {
                query_id: query_id.clone(),
                query: query.clone(),
                k: k.clone(),
                namespace: namespace.clone(),
}),
            Reducer::PurgeNnResultSimilarityAnomalies{
                confirm,
}             => __sats::bsatn::to_vec(&purge_nn_result_similarity_anomalies_reducer::PurgeNnResultSimilarityAnomaliesArgs {
                confirm: confirm.clone(),
}),
            Reducer::RecordBuoyExchangeV1{
                namespace,
                from_agent,
                to_agent,
                subject,
                evidence_hash,
                verified,
}             => __sats::bsatn::to_vec(&record_buoy_exchange_v_1_reducer::RecordBuoyExchangeV1Args {
                namespace: namespace.clone(),
                from_agent: from_agent.clone(),
                to_agent: to_agent.clone(),
                subject: subject.clone(),
                evidence_hash: evidence_hash.clone(),
                verified: verified.clone(),
}),
            Reducer::RecordToolInvocation{
                session_id,
                tool_name,
                args_hash,
                args_summary,
                success,
                duration_ms,
}             => __sats::bsatn::to_vec(&record_tool_invocation_reducer::RecordToolInvocationArgs {
                session_id: session_id.clone(),
                tool_name: tool_name.clone(),
                args_hash: args_hash.clone(),
                args_summary: args_summary.clone(),
                success: success.clone(),
                duration_ms: duration_ms.clone(),
}),
            Reducer::RegisterClaudeSession{
                session_id,
                project_path,
                project_namespace,
                transcript_path,
                model_id,
                parent_session_id,
                zellij_session,
                zellij_pane_id,
}             => __sats::bsatn::to_vec(&register_claude_session_reducer::RegisterClaudeSessionArgs {
                session_id: session_id.clone(),
                project_path: project_path.clone(),
                project_namespace: project_namespace.clone(),
                transcript_path: transcript_path.clone(),
                model_id: model_id.clone(),
                parent_session_id: parent_session_id.clone(),
                zellij_session: zellij_session.clone(),
                zellij_pane_id: zellij_pane_id.clone(),
}),
            Reducer::RegisterConsumer{
                name,
                namespace,
                transport,
}             => __sats::bsatn::to_vec(&register_consumer_reducer::RegisterConsumerArgs {
                name: name.clone(),
                namespace: namespace.clone(),
                transport: transport.clone(),
}),
            Reducer::ReinforcePathway{
                pre_id,
                post_id,
                namespace,
                delta,
}             => __sats::bsatn::to_vec(&reinforce_pathway_reducer::ReinforcePathwayArgs {
                pre_id: pre_id.clone(),
                post_id: post_id.clone(),
                namespace: namespace.clone(),
                delta: delta.clone(),
}),
            Reducer::RevokeBuoyAgentV1{
                agent_id,
                reason,
}             => __sats::bsatn::to_vec(&revoke_buoy_agent_v_1_reducer::RevokeBuoyAgentV1Args {
                agent_id: agent_id.clone(),
                reason: reason.clone(),
}),
            Reducer::SuspendBuoyAgentV1{
                agent_id,
                reason,
}             => __sats::bsatn::to_vec(&suspend_buoy_agent_v_1_reducer::SuspendBuoyAgentV1Args {
                agent_id: agent_id.clone(),
                reason: reason.clone(),
}),
            Reducer::UnregisterConsumer{
                name,
}             => __sats::bsatn::to_vec(&unregister_consumer_reducer::UnregisterConsumerArgs {
                name: name.clone(),
}),
            Reducer::VisitBuoyV1{
                namespace,
                agent_id,
                display_name,
                capabilities,
                needs,
                offerings,
                witness_hash,
                consumer_name,
}             => __sats::bsatn::to_vec(&visit_buoy_v_1_reducer::VisitBuoyV1Args {
                namespace: namespace.clone(),
                agent_id: agent_id.clone(),
                display_name: display_name.clone(),
                capabilities: capabilities.clone(),
                needs: needs.clone(),
                offerings: offerings.clone(),
                witness_hash: witness_hash.clone(),
                consumer_name: consumer_name.clone(),
}),
            Reducer::WriteMemory{
                namespace,
                modality,
                content,
                intensity,
                tensor,
                session_id,
                instance_id,
                parent_ids,
}             => __sats::bsatn::to_vec(&write_memory_reducer::WriteMemoryArgs {
                namespace: namespace.clone(),
                modality: modality.clone(),
                content: content.clone(),
                intensity: intensity.clone(),
                tensor: tensor.clone(),
                session_id: session_id.clone(),
                instance_id: instance_id.clone(),
                parent_ids: parent_ids.clone(),
}),
            Reducer::WritePathway{
                pre_id,
                post_id,
                namespace,
                weight,
                session_id,
                instance_id,
}             => __sats::bsatn::to_vec(&write_pathway_reducer::WritePathwayArgs {
                pre_id: pre_id.clone(),
                post_id: post_id.clone(),
                namespace: namespace.clone(),
                weight: weight.clone(),
                session_id: session_id.clone(),
                instance_id: instance_id.clone(),
}),
            _ => unreachable!(),
}
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    agent_registry: __sdk::TableUpdate<AgentRegistry>,
    buoy_edge: __sdk::TableUpdate<BuoyEdge>,
    buoy_listing: __sdk::TableUpdate<BuoyListing>,
    claude_session: __sdk::TableUpdate<ClaudeSession>,
    consumer: __sdk::TableUpdate<Consumer>,
    consumption_event: __sdk::TableUpdate<ConsumptionEvent>,
    cross_substrate_ref: __sdk::TableUpdate<CrossSubstrateRef>,
    decay_audit: __sdk::TableUpdate<DecayAudit>,
    ghost_memory: __sdk::TableUpdate<GhostMemory>,
    hermes_memory_context: __sdk::TableUpdate<HermesMemoryContextRow>,
    hermes_pathway_context: __sdk::TableUpdate<HermesPathwayContextRow>,
    memory: __sdk::TableUpdate<Memory>,
    nn_result: __sdk::TableUpdate<NnResult>,
    pane_context: __sdk::TableUpdate<PaneContext>,
    pathway: __sdk::TableUpdate<Pathway>,
    tool_invocation: __sdk::TableUpdate<ToolInvocation>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "agent_registry" => db_update
                    .agent_registry
                    .append(agent_registry_table::parse_table_update(table_update)?),
                "buoy_edge" => db_update
                    .buoy_edge
                    .append(buoy_edge_table::parse_table_update(table_update)?),
                "buoy_listing" => db_update
                    .buoy_listing
                    .append(buoy_listing_table::parse_table_update(table_update)?),
                "claude_session" => db_update
                    .claude_session
                    .append(claude_session_table::parse_table_update(table_update)?),
                "consumer" => db_update
                    .consumer
                    .append(consumer_table::parse_table_update(table_update)?),
                "consumption_event" => db_update
                    .consumption_event
                    .append(consumption_event_table::parse_table_update(table_update)?),
                "cross_substrate_ref" => db_update
                    .cross_substrate_ref
                    .append(cross_substrate_ref_table::parse_table_update(table_update)?),
                "decay_audit" => db_update
                    .decay_audit
                    .append(decay_audit_table::parse_table_update(table_update)?),
                "ghost_memory" => db_update
                    .ghost_memory
                    .append(ghost_memory_table::parse_table_update(table_update)?),
                "hermes_memory_context" => db_update.hermes_memory_context.append(
                    hermes_memory_context_table::parse_table_update(table_update)?,
                ),
                "hermes_pathway_context" => db_update.hermes_pathway_context.append(
                    hermes_pathway_context_table::parse_table_update(table_update)?,
                ),
                "memory" => db_update
                    .memory
                    .append(memory_table::parse_table_update(table_update)?),
                "nn_result" => db_update
                    .nn_result
                    .append(nn_result_table::parse_table_update(table_update)?),
                "pane_context" => db_update
                    .pane_context
                    .append(pane_context_table::parse_table_update(table_update)?),
                "pathway" => db_update
                    .pathway
                    .append(pathway_table::parse_table_update(table_update)?),
                "tool_invocation" => db_update
                    .tool_invocation
                    .append(tool_invocation_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.agent_registry = cache
            .apply_diff_to_table::<AgentRegistry>("agent_registry", &self.agent_registry)
            .with_updates_by_pk(|row| &row.agent_id);
        diff.buoy_edge = cache
            .apply_diff_to_table::<BuoyEdge>("buoy_edge", &self.buoy_edge)
            .with_updates_by_pk(|row| &row.key);
        diff.buoy_listing = cache
            .apply_diff_to_table::<BuoyListing>("buoy_listing", &self.buoy_listing)
            .with_updates_by_pk(|row| &row.agent_id);
        diff.claude_session = cache
            .apply_diff_to_table::<ClaudeSession>("claude_session", &self.claude_session)
            .with_updates_by_pk(|row| &row.session_id);
        diff.consumer = cache
            .apply_diff_to_table::<Consumer>("consumer", &self.consumer)
            .with_updates_by_pk(|row| &row.name);
        diff.consumption_event = cache
            .apply_diff_to_table::<ConsumptionEvent>("consumption_event", &self.consumption_event)
            .with_updates_by_pk(|row| &row.id);
        diff.cross_substrate_ref = cache
            .apply_diff_to_table::<CrossSubstrateRef>(
                "cross_substrate_ref",
                &self.cross_substrate_ref,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.decay_audit = cache
            .apply_diff_to_table::<DecayAudit>("decay_audit", &self.decay_audit)
            .with_updates_by_pk(|row| &row.id);
        diff.ghost_memory = cache
            .apply_diff_to_table::<GhostMemory>("ghost_memory", &self.ghost_memory)
            .with_updates_by_pk(|row| &row.id);
        diff.memory = cache
            .apply_diff_to_table::<Memory>("memory", &self.memory)
            .with_updates_by_pk(|row| &row.id);
        diff.nn_result = cache
            .apply_diff_to_table::<NnResult>("nn_result", &self.nn_result)
            .with_updates_by_pk(|row| &row.id);
        diff.pane_context = cache
            .apply_diff_to_table::<PaneContext>("pane_context", &self.pane_context)
            .with_updates_by_pk(|row| &row.claude_session_id);
        diff.pathway = cache
            .apply_diff_to_table::<Pathway>("pathway", &self.pathway)
            .with_updates_by_pk(|row| &row.id);
        diff.tool_invocation = cache
            .apply_diff_to_table::<ToolInvocation>("tool_invocation", &self.tool_invocation)
            .with_updates_by_pk(|row| &row.id);
        diff.hermes_memory_context = cache.apply_diff_to_table::<HermesMemoryContextRow>(
            "hermes_memory_context",
            &self.hermes_memory_context,
        );
        diff.hermes_pathway_context = cache.apply_diff_to_table::<HermesPathwayContextRow>(
            "hermes_pathway_context",
            &self.hermes_pathway_context,
        );

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "agent_registry" => db_update
                    .agent_registry
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "buoy_edge" => db_update
                    .buoy_edge
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "buoy_listing" => db_update
                    .buoy_listing
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "claude_session" => db_update
                    .claude_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "consumer" => db_update
                    .consumer
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "consumption_event" => db_update
                    .consumption_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cross_substrate_ref" => db_update
                    .cross_substrate_ref
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "decay_audit" => db_update
                    .decay_audit
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ghost_memory" => db_update
                    .ghost_memory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hermes_memory_context" => db_update
                    .hermes_memory_context
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hermes_pathway_context" => db_update
                    .hermes_pathway_context
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "memory" => db_update
                    .memory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "nn_result" => db_update
                    .nn_result
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "pane_context" => db_update
                    .pane_context
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "pathway" => db_update
                    .pathway
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tool_invocation" => db_update
                    .tool_invocation
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "agent_registry" => db_update
                    .agent_registry
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "buoy_edge" => db_update
                    .buoy_edge
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "buoy_listing" => db_update
                    .buoy_listing
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "claude_session" => db_update
                    .claude_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "consumer" => db_update
                    .consumer
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "consumption_event" => db_update
                    .consumption_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cross_substrate_ref" => db_update
                    .cross_substrate_ref
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "decay_audit" => db_update
                    .decay_audit
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ghost_memory" => db_update
                    .ghost_memory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hermes_memory_context" => db_update
                    .hermes_memory_context
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hermes_pathway_context" => db_update
                    .hermes_pathway_context
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "memory" => db_update
                    .memory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "nn_result" => db_update
                    .nn_result
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "pane_context" => db_update
                    .pane_context
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "pathway" => db_update
                    .pathway
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tool_invocation" => db_update
                    .tool_invocation
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    agent_registry: __sdk::TableAppliedDiff<'r, AgentRegistry>,
    buoy_edge: __sdk::TableAppliedDiff<'r, BuoyEdge>,
    buoy_listing: __sdk::TableAppliedDiff<'r, BuoyListing>,
    claude_session: __sdk::TableAppliedDiff<'r, ClaudeSession>,
    consumer: __sdk::TableAppliedDiff<'r, Consumer>,
    consumption_event: __sdk::TableAppliedDiff<'r, ConsumptionEvent>,
    cross_substrate_ref: __sdk::TableAppliedDiff<'r, CrossSubstrateRef>,
    decay_audit: __sdk::TableAppliedDiff<'r, DecayAudit>,
    ghost_memory: __sdk::TableAppliedDiff<'r, GhostMemory>,
    hermes_memory_context: __sdk::TableAppliedDiff<'r, HermesMemoryContextRow>,
    hermes_pathway_context: __sdk::TableAppliedDiff<'r, HermesPathwayContextRow>,
    memory: __sdk::TableAppliedDiff<'r, Memory>,
    nn_result: __sdk::TableAppliedDiff<'r, NnResult>,
    pane_context: __sdk::TableAppliedDiff<'r, PaneContext>,
    pathway: __sdk::TableAppliedDiff<'r, Pathway>,
    tool_invocation: __sdk::TableAppliedDiff<'r, ToolInvocation>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AgentRegistry>(
            "agent_registry",
            &self.agent_registry,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BuoyEdge>("buoy_edge", &self.buoy_edge, event);
        callbacks.invoke_table_row_callbacks::<BuoyListing>(
            "buoy_listing",
            &self.buoy_listing,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ClaudeSession>(
            "claude_session",
            &self.claude_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Consumer>("consumer", &self.consumer, event);
        callbacks.invoke_table_row_callbacks::<ConsumptionEvent>(
            "consumption_event",
            &self.consumption_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CrossSubstrateRef>(
            "cross_substrate_ref",
            &self.cross_substrate_ref,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DecayAudit>("decay_audit", &self.decay_audit, event);
        callbacks.invoke_table_row_callbacks::<GhostMemory>(
            "ghost_memory",
            &self.ghost_memory,
            event,
        );
        callbacks.invoke_table_row_callbacks::<HermesMemoryContextRow>(
            "hermes_memory_context",
            &self.hermes_memory_context,
            event,
        );
        callbacks.invoke_table_row_callbacks::<HermesPathwayContextRow>(
            "hermes_pathway_context",
            &self.hermes_pathway_context,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Memory>("memory", &self.memory, event);
        callbacks.invoke_table_row_callbacks::<NnResult>("nn_result", &self.nn_result, event);
        callbacks.invoke_table_row_callbacks::<PaneContext>(
            "pane_context",
            &self.pane_context,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Pathway>("pathway", &self.pathway, event);
        callbacks.invoke_table_row_callbacks::<ToolInvocation>(
            "tool_invocation",
            &self.tool_invocation,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        agent_registry_table::register_table(client_cache);
        buoy_edge_table::register_table(client_cache);
        buoy_listing_table::register_table(client_cache);
        claude_session_table::register_table(client_cache);
        consumer_table::register_table(client_cache);
        consumption_event_table::register_table(client_cache);
        cross_substrate_ref_table::register_table(client_cache);
        decay_audit_table::register_table(client_cache);
        ghost_memory_table::register_table(client_cache);
        hermes_memory_context_table::register_table(client_cache);
        hermes_pathway_context_table::register_table(client_cache);
        memory_table::register_table(client_cache);
        nn_result_table::register_table(client_cache);
        pane_context_table::register_table(client_cache);
        pathway_table::register_table(client_cache);
        tool_invocation_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "agent_registry",
        "buoy_edge",
        "buoy_listing",
        "claude_session",
        "consumer",
        "consumption_event",
        "cross_substrate_ref",
        "decay_audit",
        "ghost_memory",
        "hermes_memory_context",
        "hermes_pathway_context",
        "memory",
        "nn_result",
        "pane_context",
        "pathway",
        "tool_invocation",
    ];
}
