// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct NearestNeighborArgs {
    pub query_id: String,
    pub query: Vec<f32>,
    pub k: u32,
    pub namespace: String,
}

impl From<NearestNeighborArgs> for super::Reducer {
    fn from(args: NearestNeighborArgs) -> Self {
        Self::NearestNeighbor {
            query_id: args.query_id,
            query: args.query,
            k: args.k,
            namespace: args.namespace,
        }
    }
}

impl __sdk::InModule for NearestNeighborArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `nearest_neighbor`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait nearest_neighbor {
    /// Request that the remote module invoke the reducer `nearest_neighbor` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`nearest_neighbor:nearest_neighbor_then`] to run a callback after the reducer completes.
    fn nearest_neighbor(
        &self,
        query_id: String,
        query: Vec<f32>,
        k: u32,
        namespace: String,
    ) -> __sdk::Result<()> {
        self.nearest_neighbor_then(query_id, query, k, namespace, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `nearest_neighbor` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn nearest_neighbor_then(
        &self,
        query_id: String,
        query: Vec<f32>,
        k: u32,
        namespace: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl nearest_neighbor for super::RemoteReducers {
    fn nearest_neighbor_then(
        &self,
        query_id: String,
        query: Vec<f32>,
        k: u32,
        namespace: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            NearestNeighborArgs {
                query_id,
                query,
                k,
                namespace,
            },
            callback,
        )
    }
}
