// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PaneContext {
    pub claude_session_id: String,
    pub zellij_session: String,
    pub tab_name: String,
    pub pane_id: String,
    pub sphere_id: Option<String>,
    pub registered_at: __sdk::Timestamp,
}

impl __sdk::InModule for PaneContext {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PaneContext`.
///
/// Provides typed access to columns for query building.
pub struct PaneContextCols {
    pub claude_session_id: __sdk::__query_builder::Col<PaneContext, String>,
    pub zellij_session: __sdk::__query_builder::Col<PaneContext, String>,
    pub tab_name: __sdk::__query_builder::Col<PaneContext, String>,
    pub pane_id: __sdk::__query_builder::Col<PaneContext, String>,
    pub sphere_id: __sdk::__query_builder::Col<PaneContext, Option<String>>,
    pub registered_at: __sdk::__query_builder::Col<PaneContext, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PaneContext {
    type Cols = PaneContextCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PaneContextCols {
            claude_session_id: __sdk::__query_builder::Col::new(table_name, "claude_session_id"),
            zellij_session: __sdk::__query_builder::Col::new(table_name, "zellij_session"),
            tab_name: __sdk::__query_builder::Col::new(table_name, "tab_name"),
            pane_id: __sdk::__query_builder::Col::new(table_name, "pane_id"),
            sphere_id: __sdk::__query_builder::Col::new(table_name, "sphere_id"),
            registered_at: __sdk::__query_builder::Col::new(table_name, "registered_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PaneContext`.
///
/// Provides typed access to indexed columns for query building.
pub struct PaneContextIxCols {
    pub claude_session_id: __sdk::__query_builder::IxCol<PaneContext, String>,
}

impl __sdk::__query_builder::HasIxCols for PaneContext {
    type IxCols = PaneContextIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PaneContextIxCols {
            claude_session_id: __sdk::__query_builder::IxCol::new(table_name, "claude_session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PaneContext {}
