// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pane_context_type::PaneContext;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pane_context`.
///
/// Obtain a handle from the [`PaneContextTableAccess::pane_context`] method on [`super::RemoteTables`],
/// like `ctx.db.pane_context()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pane_context().on_insert(...)`.
pub struct PaneContextTableHandle<'ctx> {
    imp: __sdk::TableHandle<PaneContext>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pane_context`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PaneContextTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PaneContextTableHandle`], which mediates access to the table `pane_context`.
    fn pane_context(&self) -> PaneContextTableHandle<'_>;
}

impl PaneContextTableAccess for super::RemoteTables {
    fn pane_context(&self) -> PaneContextTableHandle<'_> {
        PaneContextTableHandle {
            imp: self.imp.get_table::<PaneContext>("pane_context"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PaneContextInsertCallbackId(__sdk::CallbackId);
pub struct PaneContextDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PaneContextTableHandle<'ctx> {
    type Row = PaneContext;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PaneContext> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PaneContextInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaneContextInsertCallbackId {
        PaneContextInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PaneContextInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PaneContextDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaneContextDeleteCallbackId {
        PaneContextDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PaneContextDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PaneContextUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PaneContextTableHandle<'ctx> {
    type UpdateCallbackId = PaneContextUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PaneContextUpdateCallbackId {
        PaneContextUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PaneContextUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `claude_session_id` unique index on the table `pane_context`,
/// which allows point queries on the field of the same name
/// via the [`PaneContextClaudeSessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pane_context().claude_session_id().find(...)`.
pub struct PaneContextClaudeSessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PaneContext, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PaneContextTableHandle<'ctx> {
    /// Get a handle on the `claude_session_id` unique index on the table `pane_context`.
    pub fn claude_session_id(&self) -> PaneContextClaudeSessionIdUnique<'ctx> {
        PaneContextClaudeSessionIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<String>("claude_session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PaneContextClaudeSessionIdUnique<'ctx> {
    /// Find the subscribed row whose `claude_session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PaneContext> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PaneContext>("pane_context");
    _table.add_unique_constraint::<String>("claude_session_id", |row| &row.claude_session_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PaneContext>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PaneContext>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PaneContext`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait pane_contextQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PaneContext`.
    fn pane_context(&self) -> __sdk::__query_builder::Table<PaneContext>;
}

impl pane_contextQueryTableAccess for __sdk::QueryTableAccessor {
    fn pane_context(&self) -> __sdk::__query_builder::Table<PaneContext> {
        __sdk::__query_builder::Table::new("pane_context")
    }
}
