// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PathwayLookup {
    pub key: String,
    pub namespace: String,
    pub pathway_id: u64,
}

impl __sdk::InModule for PathwayLookup {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PathwayLookup`.
///
/// Provides typed access to columns for query building.
pub struct PathwayLookupCols {
    pub key: __sdk::__query_builder::Col<PathwayLookup, String>,
    pub namespace: __sdk::__query_builder::Col<PathwayLookup, String>,
    pub pathway_id: __sdk::__query_builder::Col<PathwayLookup, u64>,
}

impl __sdk::__query_builder::HasCols for PathwayLookup {
    type Cols = PathwayLookupCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PathwayLookupCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            pathway_id: __sdk::__query_builder::Col::new(table_name, "pathway_id"),
        }
    }
}

/// Indexed column accessor struct for the table `PathwayLookup`.
///
/// Provides typed access to indexed columns for query building.
pub struct PathwayLookupIxCols {
    pub key: __sdk::__query_builder::IxCol<PathwayLookup, String>,
    pub namespace: __sdk::__query_builder::IxCol<PathwayLookup, String>,
}

impl __sdk::__query_builder::HasIxCols for PathwayLookup {
    type IxCols = PathwayLookupIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PathwayLookupIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PathwayLookup {}
