// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Pathway {
    pub id: u64,
    pub pre_id: String,
    pub post_id: String,
    pub namespace: String,
    pub weight: f32,
    pub created_at: __sdk::Timestamp,
    pub last_reinforced: __sdk::Timestamp,
    pub reinforce_count: u32,
    pub session_id: String,
    pub instance_id: Option<String>,
}

impl __sdk::InModule for Pathway {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Pathway`.
///
/// Provides typed access to columns for query building.
pub struct PathwayCols {
    pub id: __sdk::__query_builder::Col<Pathway, u64>,
    pub pre_id: __sdk::__query_builder::Col<Pathway, String>,
    pub post_id: __sdk::__query_builder::Col<Pathway, String>,
    pub namespace: __sdk::__query_builder::Col<Pathway, String>,
    pub weight: __sdk::__query_builder::Col<Pathway, f32>,
    pub created_at: __sdk::__query_builder::Col<Pathway, __sdk::Timestamp>,
    pub last_reinforced: __sdk::__query_builder::Col<Pathway, __sdk::Timestamp>,
    pub reinforce_count: __sdk::__query_builder::Col<Pathway, u32>,
    pub session_id: __sdk::__query_builder::Col<Pathway, String>,
    pub instance_id: __sdk::__query_builder::Col<Pathway, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Pathway {
    type Cols = PathwayCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PathwayCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            pre_id: __sdk::__query_builder::Col::new(table_name, "pre_id"),
            post_id: __sdk::__query_builder::Col::new(table_name, "post_id"),
            namespace: __sdk::__query_builder::Col::new(table_name, "namespace"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_reinforced: __sdk::__query_builder::Col::new(table_name, "last_reinforced"),
            reinforce_count: __sdk::__query_builder::Col::new(table_name, "reinforce_count"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Pathway`.
///
/// Provides typed access to indexed columns for query building.
pub struct PathwayIxCols {
    pub id: __sdk::__query_builder::IxCol<Pathway, u64>,
    pub namespace: __sdk::__query_builder::IxCol<Pathway, String>,
    pub post_id: __sdk::__query_builder::IxCol<Pathway, String>,
    pub pre_id: __sdk::__query_builder::IxCol<Pathway, String>,
}

impl __sdk::__query_builder::HasIxCols for Pathway {
    type IxCols = PathwayIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PathwayIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            namespace: __sdk::__query_builder::IxCol::new(table_name, "namespace"),
            post_id: __sdk::__query_builder::IxCol::new(table_name, "post_id"),
            pre_id: __sdk::__query_builder::IxCol::new(table_name, "pre_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Pathway {}
