// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pathway_type::Pathway;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pathway`.
///
/// Obtain a handle from the [`PathwayTableAccess::pathway`] method on [`super::RemoteTables`],
/// like `ctx.db.pathway()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pathway().on_insert(...)`.
pub struct PathwayTableHandle<'ctx> {
    imp: __sdk::TableHandle<Pathway>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pathway`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PathwayTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PathwayTableHandle`], which mediates access to the table `pathway`.
    fn pathway(&self) -> PathwayTableHandle<'_>;
}

impl PathwayTableAccess for super::RemoteTables {
    fn pathway(&self) -> PathwayTableHandle<'_> {
        PathwayTableHandle {
            imp: self.imp.get_table::<Pathway>("pathway"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PathwayInsertCallbackId(__sdk::CallbackId);
pub struct PathwayDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PathwayTableHandle<'ctx> {
    type Row = Pathway;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Pathway> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PathwayInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PathwayInsertCallbackId {
        PathwayInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PathwayInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PathwayDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PathwayDeleteCallbackId {
        PathwayDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PathwayDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PathwayUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PathwayTableHandle<'ctx> {
    type UpdateCallbackId = PathwayUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PathwayUpdateCallbackId {
        PathwayUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PathwayUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `pathway`,
/// which allows point queries on the field of the same name
/// via the [`PathwayIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pathway().id().find(...)`.
pub struct PathwayIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Pathway, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PathwayTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `pathway`.
    pub fn id(&self) -> PathwayIdUnique<'ctx> {
        PathwayIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PathwayIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Pathway> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Pathway>("pathway");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Pathway>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Pathway>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Pathway`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait pathwayQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Pathway`.
    fn pathway(&self) -> __sdk::__query_builder::Table<Pathway>;
}

impl pathwayQueryTableAccess for __sdk::QueryTableAccessor {
    fn pathway(&self) -> __sdk::__query_builder::Table<Pathway> {
        __sdk::__query_builder::Table::new("pathway")
    }
}
