// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordBuoyExchangeV1Args {
    pub namespace: String,
    pub from_agent: String,
    pub to_agent: String,
    pub subject: String,
    pub evidence_hash: String,
    pub verified: bool,
}

impl From<RecordBuoyExchangeV1Args> for super::Reducer {
    fn from(args: RecordBuoyExchangeV1Args) -> Self {
        Self::RecordBuoyExchangeV1 {
            namespace: args.namespace,
            from_agent: args.from_agent,
            to_agent: args.to_agent,
            subject: args.subject,
            evidence_hash: args.evidence_hash,
            verified: args.verified,
        }
    }
}

impl __sdk::InModule for RecordBuoyExchangeV1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_buoy_exchange_v_1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_buoy_exchange_v_1 {
    /// Request that the remote module invoke the reducer `record_buoy_exchange_v_1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_buoy_exchange_v_1:record_buoy_exchange_v_1_then`] to run a callback after the reducer completes.
    fn record_buoy_exchange_v_1(
        &self,
        namespace: String,
        from_agent: String,
        to_agent: String,
        subject: String,
        evidence_hash: String,
        verified: bool,
    ) -> __sdk::Result<()> {
        self.record_buoy_exchange_v_1_then(
            namespace,
            from_agent,
            to_agent,
            subject,
            evidence_hash,
            verified,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_buoy_exchange_v_1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_buoy_exchange_v_1_then(
        &self,
        namespace: String,
        from_agent: String,
        to_agent: String,
        subject: String,
        evidence_hash: String,
        verified: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl record_buoy_exchange_v_1 for super::RemoteReducers {
    fn record_buoy_exchange_v_1_then(
        &self,
        namespace: String,
        from_agent: String,
        to_agent: String,
        subject: String,
        evidence_hash: String,
        verified: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordBuoyExchangeV1Args {
                namespace,
                from_agent,
                to_agent,
                subject,
                evidence_hash,
                verified,
            },
            callback,
        )
    }
}
