// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordToolInvocationArgs {
    pub session_id: String,
    pub tool_name: String,
    pub args_hash: String,
    pub args_summary: Option<String>,
    pub success: bool,
    pub duration_ms: Option<u64>,
}

impl From<RecordToolInvocationArgs> for super::Reducer {
    fn from(args: RecordToolInvocationArgs) -> Self {
        Self::RecordToolInvocation {
            session_id: args.session_id,
            tool_name: args.tool_name,
            args_hash: args.args_hash,
            args_summary: args.args_summary,
            success: args.success,
            duration_ms: args.duration_ms,
        }
    }
}

impl __sdk::InModule for RecordToolInvocationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_tool_invocation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_tool_invocation {
    /// Request that the remote module invoke the reducer `record_tool_invocation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_tool_invocation:record_tool_invocation_then`] to run a callback after the reducer completes.
    fn record_tool_invocation(
        &self,
        session_id: String,
        tool_name: String,
        args_hash: String,
        args_summary: Option<String>,
        success: bool,
        duration_ms: Option<u64>,
    ) -> __sdk::Result<()> {
        self.record_tool_invocation_then(
            session_id,
            tool_name,
            args_hash,
            args_summary,
            success,
            duration_ms,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_tool_invocation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_tool_invocation_then(
        &self,
        session_id: String,
        tool_name: String,
        args_hash: String,
        args_summary: Option<String>,
        success: bool,
        duration_ms: Option<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl record_tool_invocation for super::RemoteReducers {
    fn record_tool_invocation_then(
        &self,
        session_id: String,
        tool_name: String,
        args_hash: String,
        args_summary: Option<String>,
        success: bool,
        duration_ms: Option<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordToolInvocationArgs {
                session_id,
                tool_name,
                args_hash,
                args_summary,
                success,
                duration_ms,
            },
            callback,
        )
    }
}
