// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterClaudeSessionArgs {
    pub session_id: String,
    pub project_path: String,
    pub project_namespace: String,
    pub transcript_path: Option<String>,
    pub model_id: Option<String>,
    pub parent_session_id: Option<String>,
    pub zellij_session: Option<String>,
    pub zellij_pane_id: Option<String>,
}

impl From<RegisterClaudeSessionArgs> for super::Reducer {
    fn from(args: RegisterClaudeSessionArgs) -> Self {
        Self::RegisterClaudeSession {
            session_id: args.session_id,
            project_path: args.project_path,
            project_namespace: args.project_namespace,
            transcript_path: args.transcript_path,
            model_id: args.model_id,
            parent_session_id: args.parent_session_id,
            zellij_session: args.zellij_session,
            zellij_pane_id: args.zellij_pane_id,
        }
    }
}

impl __sdk::InModule for RegisterClaudeSessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_claude_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_claude_session {
    /// Request that the remote module invoke the reducer `register_claude_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_claude_session:register_claude_session_then`] to run a callback after the reducer completes.
    fn register_claude_session(
        &self,
        session_id: String,
        project_path: String,
        project_namespace: String,
        transcript_path: Option<String>,
        model_id: Option<String>,
        parent_session_id: Option<String>,
        zellij_session: Option<String>,
        zellij_pane_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.register_claude_session_then(
            session_id,
            project_path,
            project_namespace,
            transcript_path,
            model_id,
            parent_session_id,
            zellij_session,
            zellij_pane_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_claude_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_claude_session_then(
        &self,
        session_id: String,
        project_path: String,
        project_namespace: String,
        transcript_path: Option<String>,
        model_id: Option<String>,
        parent_session_id: Option<String>,
        zellij_session: Option<String>,
        zellij_pane_id: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl register_claude_session for super::RemoteReducers {
    fn register_claude_session_then(
        &self,
        session_id: String,
        project_path: String,
        project_namespace: String,
        transcript_path: Option<String>,
        model_id: Option<String>,
        parent_session_id: Option<String>,
        zellij_session: Option<String>,
        zellij_pane_id: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterClaudeSessionArgs {
                session_id,
                project_path,
                project_namespace,
                transcript_path,
                model_id,
                parent_session_id,
                zellij_session,
                zellij_pane_id,
            },
            callback,
        )
    }
}
