// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterConsumerArgs {
    pub name: String,
    pub namespace: String,
    pub transport: String,
}

impl From<RegisterConsumerArgs> for super::Reducer {
    fn from(args: RegisterConsumerArgs) -> Self {
        Self::RegisterConsumer {
            name: args.name,
            namespace: args.namespace,
            transport: args.transport,
        }
    }
}

impl __sdk::InModule for RegisterConsumerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_consumer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_consumer {
    /// Request that the remote module invoke the reducer `register_consumer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_consumer:register_consumer_then`] to run a callback after the reducer completes.
    fn register_consumer(
        &self,
        name: String,
        namespace: String,
        transport: String,
    ) -> __sdk::Result<()> {
        self.register_consumer_then(name, namespace, transport, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_consumer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_consumer_then(
        &self,
        name: String,
        namespace: String,
        transport: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl register_consumer for super::RemoteReducers {
    fn register_consumer_then(
        &self,
        name: String,
        namespace: String,
        transport: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterConsumerArgs {
                name,
                namespace,
                transport,
            },
            callback,
        )
    }
}
