// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReinforcePathwayArgs {
    pub pre_id: String,
    pub post_id: String,
    pub namespace: String,
    pub delta: f32,
}

impl From<ReinforcePathwayArgs> for super::Reducer {
    fn from(args: ReinforcePathwayArgs) -> Self {
        Self::ReinforcePathway {
            pre_id: args.pre_id,
            post_id: args.post_id,
            namespace: args.namespace,
            delta: args.delta,
        }
    }
}

impl __sdk::InModule for ReinforcePathwayArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `reinforce_pathway`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait reinforce_pathway {
    /// Request that the remote module invoke the reducer `reinforce_pathway` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`reinforce_pathway:reinforce_pathway_then`] to run a callback after the reducer completes.
    fn reinforce_pathway(
        &self,
        pre_id: String,
        post_id: String,
        namespace: String,
        delta: f32,
    ) -> __sdk::Result<()> {
        self.reinforce_pathway_then(pre_id, post_id, namespace, delta, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `reinforce_pathway` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn reinforce_pathway_then(
        &self,
        pre_id: String,
        post_id: String,
        namespace: String,
        delta: f32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl reinforce_pathway for super::RemoteReducers {
    fn reinforce_pathway_then(
        &self,
        pre_id: String,
        post_id: String,
        namespace: String,
        delta: f32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReinforcePathwayArgs {
                pre_id,
                post_id,
                namespace,
                delta,
            },
            callback,
        )
    }
}
