// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokeBuoyAgentV1Args {
    pub agent_id: String,
    pub reason: String,
}

impl From<RevokeBuoyAgentV1Args> for super::Reducer {
    fn from(args: RevokeBuoyAgentV1Args) -> Self {
        Self::RevokeBuoyAgentV1 {
            agent_id: args.agent_id,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for RevokeBuoyAgentV1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_buoy_agent_v_1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_buoy_agent_v_1 {
    /// Request that the remote module invoke the reducer `revoke_buoy_agent_v_1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`revoke_buoy_agent_v_1:revoke_buoy_agent_v_1_then`] to run a callback after the reducer completes.
    fn revoke_buoy_agent_v_1(&self, agent_id: String, reason: String) -> __sdk::Result<()> {
        self.revoke_buoy_agent_v_1_then(agent_id, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revoke_buoy_agent_v_1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revoke_buoy_agent_v_1_then(
        &self,
        agent_id: String,
        reason: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl revoke_buoy_agent_v_1 for super::RemoteReducers {
    fn revoke_buoy_agent_v_1_then(
        &self,
        agent_id: String,
        reason: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RevokeBuoyAgentV1Args { agent_id, reason }, callback)
    }
}
