// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ToolInvocation {
    pub id: u64,
    pub session_id: String,
    pub tool_name: String,
    pub args_hash: String,
    pub args_summary: Option<String>,
    pub success: bool,
    pub ts: __sdk::Timestamp,
    pub duration_ms: Option<u64>,
}

impl __sdk::InModule for ToolInvocation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ToolInvocation`.
///
/// Provides typed access to columns for query building.
pub struct ToolInvocationCols {
    pub id: __sdk::__query_builder::Col<ToolInvocation, u64>,
    pub session_id: __sdk::__query_builder::Col<ToolInvocation, String>,
    pub tool_name: __sdk::__query_builder::Col<ToolInvocation, String>,
    pub args_hash: __sdk::__query_builder::Col<ToolInvocation, String>,
    pub args_summary: __sdk::__query_builder::Col<ToolInvocation, Option<String>>,
    pub success: __sdk::__query_builder::Col<ToolInvocation, bool>,
    pub ts: __sdk::__query_builder::Col<ToolInvocation, __sdk::Timestamp>,
    pub duration_ms: __sdk::__query_builder::Col<ToolInvocation, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for ToolInvocation {
    type Cols = ToolInvocationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ToolInvocationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            tool_name: __sdk::__query_builder::Col::new(table_name, "tool_name"),
            args_hash: __sdk::__query_builder::Col::new(table_name, "args_hash"),
            args_summary: __sdk::__query_builder::Col::new(table_name, "args_summary"),
            success: __sdk::__query_builder::Col::new(table_name, "success"),
            ts: __sdk::__query_builder::Col::new(table_name, "ts"),
            duration_ms: __sdk::__query_builder::Col::new(table_name, "duration_ms"),
        }
    }
}

/// Indexed column accessor struct for the table `ToolInvocation`.
///
/// Provides typed access to indexed columns for query building.
pub struct ToolInvocationIxCols {
    pub id: __sdk::__query_builder::IxCol<ToolInvocation, u64>,
    pub session_id: __sdk::__query_builder::IxCol<ToolInvocation, String>,
}

impl __sdk::__query_builder::HasIxCols for ToolInvocation {
    type IxCols = ToolInvocationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ToolInvocationIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ToolInvocation {}
