// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tool_invocation_type::ToolInvocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tool_invocation`.
///
/// Obtain a handle from the [`ToolInvocationTableAccess::tool_invocation`] method on [`super::RemoteTables`],
/// like `ctx.db.tool_invocation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tool_invocation().on_insert(...)`.
pub struct ToolInvocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<ToolInvocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tool_invocation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ToolInvocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ToolInvocationTableHandle`], which mediates access to the table `tool_invocation`.
    fn tool_invocation(&self) -> ToolInvocationTableHandle<'_>;
}

impl ToolInvocationTableAccess for super::RemoteTables {
    fn tool_invocation(&self) -> ToolInvocationTableHandle<'_> {
        ToolInvocationTableHandle {
            imp: self.imp.get_table::<ToolInvocation>("tool_invocation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ToolInvocationInsertCallbackId(__sdk::CallbackId);
pub struct ToolInvocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ToolInvocationTableHandle<'ctx> {
    type Row = ToolInvocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ToolInvocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ToolInvocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ToolInvocationInsertCallbackId {
        ToolInvocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ToolInvocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ToolInvocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ToolInvocationDeleteCallbackId {
        ToolInvocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ToolInvocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ToolInvocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ToolInvocationTableHandle<'ctx> {
    type UpdateCallbackId = ToolInvocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ToolInvocationUpdateCallbackId {
        ToolInvocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ToolInvocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `tool_invocation`,
/// which allows point queries on the field of the same name
/// via the [`ToolInvocationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tool_invocation().id().find(...)`.
pub struct ToolInvocationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ToolInvocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ToolInvocationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `tool_invocation`.
    pub fn id(&self) -> ToolInvocationIdUnique<'ctx> {
        ToolInvocationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ToolInvocationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ToolInvocation> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ToolInvocation>("tool_invocation");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ToolInvocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ToolInvocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ToolInvocation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait tool_invocationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ToolInvocation`.
    fn tool_invocation(&self) -> __sdk::__query_builder::Table<ToolInvocation>;
}

impl tool_invocationQueryTableAccess for __sdk::QueryTableAccessor {
    fn tool_invocation(&self) -> __sdk::__query_builder::Table<ToolInvocation> {
        __sdk::__query_builder::Table::new("tool_invocation")
    }
}
