// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct VisitBuoyV1Args {
    pub namespace: String,
    pub agent_id: String,
    pub display_name: String,
    pub capabilities: Vec<String>,
    pub needs: Vec<String>,
    pub offerings: Vec<String>,
    pub witness_hash: Option<String>,
    pub consumer_name: Option<String>,
}

impl From<VisitBuoyV1Args> for super::Reducer {
    fn from(args: VisitBuoyV1Args) -> Self {
        Self::VisitBuoyV1 {
            namespace: args.namespace,
            agent_id: args.agent_id,
            display_name: args.display_name,
            capabilities: args.capabilities,
            needs: args.needs,
            offerings: args.offerings,
            witness_hash: args.witness_hash,
            consumer_name: args.consumer_name,
        }
    }
}

impl __sdk::InModule for VisitBuoyV1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `visit_buoy_v_1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait visit_buoy_v_1 {
    /// Request that the remote module invoke the reducer `visit_buoy_v_1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`visit_buoy_v_1:visit_buoy_v_1_then`] to run a callback after the reducer completes.
    fn visit_buoy_v_1(
        &self,
        namespace: String,
        agent_id: String,
        display_name: String,
        capabilities: Vec<String>,
        needs: Vec<String>,
        offerings: Vec<String>,
        witness_hash: Option<String>,
        consumer_name: Option<String>,
    ) -> __sdk::Result<()> {
        self.visit_buoy_v_1_then(
            namespace,
            agent_id,
            display_name,
            capabilities,
            needs,
            offerings,
            witness_hash,
            consumer_name,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `visit_buoy_v_1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn visit_buoy_v_1_then(
        &self,
        namespace: String,
        agent_id: String,
        display_name: String,
        capabilities: Vec<String>,
        needs: Vec<String>,
        offerings: Vec<String>,
        witness_hash: Option<String>,
        consumer_name: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl visit_buoy_v_1 for super::RemoteReducers {
    fn visit_buoy_v_1_then(
        &self,
        namespace: String,
        agent_id: String,
        display_name: String,
        capabilities: Vec<String>,
        needs: Vec<String>,
        offerings: Vec<String>,
        witness_hash: Option<String>,
        consumer_name: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            VisitBuoyV1Args {
                namespace,
                agent_id,
                display_name,
                capabilities,
                needs,
                offerings,
                witness_hash,
                consumer_name,
            },
            callback,
        )
    }
}
