// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WritePathwayArgs {
    pub pre_id: String,
    pub post_id: String,
    pub namespace: String,
    pub weight: f32,
    pub session_id: String,
    pub instance_id: Option<String>,
}

impl From<WritePathwayArgs> for super::Reducer {
    fn from(args: WritePathwayArgs) -> Self {
        Self::WritePathway {
            pre_id: args.pre_id,
            post_id: args.post_id,
            namespace: args.namespace,
            weight: args.weight,
            session_id: args.session_id,
            instance_id: args.instance_id,
        }
    }
}

impl __sdk::InModule for WritePathwayArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `write_pathway`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait write_pathway {
    /// Request that the remote module invoke the reducer `write_pathway` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`write_pathway:write_pathway_then`] to run a callback after the reducer completes.
    fn write_pathway(
        &self,
        pre_id: String,
        post_id: String,
        namespace: String,
        weight: f32,
        session_id: String,
        instance_id: Option<String>,
    ) -> __sdk::Result<()> {
        self.write_pathway_then(
            pre_id,
            post_id,
            namespace,
            weight,
            session_id,
            instance_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `write_pathway` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn write_pathway_then(
        &self,
        pre_id: String,
        post_id: String,
        namespace: String,
        weight: f32,
        session_id: String,
        instance_id: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl write_pathway for super::RemoteReducers {
    fn write_pathway_then(
        &self,
        pre_id: String,
        post_id: String,
        namespace: String,
        weight: f32,
        session_id: String,
        instance_id: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            WritePathwayArgs {
                pre_id,
                post_id,
                namespace,
                weight,
                session_id,
                instance_id,
            },
            callback,
        )
    }
}
