// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WriteMemoryArgs {
    pub namespace: String,
    pub modality: String,
    pub content: String,
    pub intensity: f32,
    pub tensor: Option<Vec<f32>>,
    pub session_id: String,
    pub instance_id: Option<String>,
    pub parent_ids: Vec<u64>,
}

impl From<WriteMemoryArgs> for super::Reducer {
    fn from(args: WriteMemoryArgs) -> Self {
        Self::WriteMemory {
            namespace: args.namespace,
            modality: args.modality,
            content: args.content,
            intensity: args.intensity,
            tensor: args.tensor,
            session_id: args.session_id,
            instance_id: args.instance_id,
            parent_ids: args.parent_ids,
        }
    }
}

impl __sdk::InModule for WriteMemoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `write_memory`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait write_memory {
    /// Request that the remote module invoke the reducer `write_memory` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`write_memory:write_memory_then`] to run a callback after the reducer completes.
    fn write_memory(
        &self,
        namespace: String,
        modality: String,
        content: String,
        intensity: f32,
        tensor: Option<Vec<f32>>,
        session_id: String,
        instance_id: Option<String>,
        parent_ids: Vec<u64>,
    ) -> __sdk::Result<()> {
        self.write_memory_then(
            namespace,
            modality,
            content,
            intensity,
            tensor,
            session_id,
            instance_id,
            parent_ids,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `write_memory` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn write_memory_then(
        &self,
        namespace: String,
        modality: String,
        content: String,
        intensity: f32,
        tensor: Option<Vec<f32>>,
        session_id: String,
        instance_id: Option<String>,
        parent_ids: Vec<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl write_memory for super::RemoteReducers {
    fn write_memory_then(
        &self,
        namespace: String,
        modality: String,
        content: String,
        intensity: f32,
        tensor: Option<Vec<f32>>,
        session_id: String,
        instance_id: Option<String>,
        parent_ids: Vec<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            WriteMemoryArgs {
                namespace,
                modality,
                content,
                intensity,
                tensor,
                session_id,
                instance_id,
                parent_ids,
            },
            callback,
        )
    }
}
